import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'
import ts from 'typescript'
const root = new URL('../../', import.meta.url)
const input = new URL('contracts/rest/openapi.json', root)
const output = new URL('packages/protocol/src/rest.ts', root)
const schema = JSON.parse(readFileSync(input, 'utf8'))
const optionalBodies = new Set()
for (const path of Object.values(schema.paths)) {
  for (const operation of Object.values(path)) {
    for (const [status, response] of Object.entries(operation.responses ?? {})) {
      if (response['x-empty-body-allowed']) optionalBodies.add(`${operation.operationId}/${status}`)
    }
  }
}
const ast = await openapiTS(schema, {
  alphabetize: true,
  transform(value) {
    // Binary HTTP payloads are not base64 strings. Web transports use Blob/FormData.
    if (value.format === 'binary') return ts.factory.createTypeReferenceNode('Blob')
  },
})
const name = node => node.name?.text
const withType = (node, type) => ts.factory.updatePropertySignature(node, node.modifiers, node.name, node.questionToken, type)
const visited = new Set()
// OpenAPI permits a response without a body, but openapi-typescript makes content
// required whenever a media type is present. Preserve our explicit mixed-body extension.
const patched = ast.map(node => {
  if (!ts.isInterfaceDeclaration(node) || node.name.text !== 'operations') return node
  const members = node.members.map(operation => {
    if (!ts.isPropertySignature(operation) || !ts.isTypeLiteralNode(operation.type)) return operation
    const fields = operation.type.members.map(field => {
      if (name(field) !== 'responses' || !ts.isTypeLiteralNode(field.type)) return field
      return withType(field, ts.factory.createTypeLiteralNode(field.type.members.map(response => {
        const key = `${name(operation)}/${name(response)}`
        if (!optionalBodies.has(key) || !ts.isTypeLiteralNode(response.type)) return response
        visited.add(key)
        return withType(response, ts.factory.createTypeLiteralNode(response.type.members.map(content =>
          name(content) === 'content'
            ? ts.factory.updatePropertySignature(content, content.modifiers, content.name, ts.factory.createToken(ts.SyntaxKind.QuestionToken), content.type)
            : content,
        )))
      })))
    })
    return withType(operation, ts.factory.createTypeLiteralNode(fields))
  })
  return ts.factory.updateInterfaceDeclaration(node, node.modifiers, node.name, node.typeParameters, node.heritageClauses, members)
})
if (visited.size !== optionalBodies.size) throw new Error('Generator did not preserve all optional response bodies')
const expected = '// Generated by npm --prefix tooling/contracts run generate. Do not edit.\n' + astToString(patched)
if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== expected) throw new Error('REST types are stale; npm --prefix tooling/contracts run generate')
} else {
  writeFileSync(output, expected)
}
console.log(`REST types verified: ${fileURLToPath(output)}`)
