// Generated by tooling/workspace.py generate. Do not edit.
// ignore_for_file: constant_identifier_names
import 'wire_validation.dart';

class RestOperation {
  const RestOperation(this.method, this.path, this.relativePath);
  final String method, path, relativePath;
  String atBase(String base) => '${base.replaceFirst(RegExp(r'/$'), '')}$relativePath';
}

abstract final class RestOperations {
  static const login = RestOperation('POST', '/api/v1/auth/login', '/auth/login');
  static const refreshToken = RestOperation('POST', '/api/v1/auth/refresh', '/auth/refresh');
  static const logout = RestOperation('POST', '/api/v1/auth/logout', '/auth/logout');
  static const register_1 = RestOperation('POST', '/api/v1/auth/register', '/auth/register');
  static const getConversationSummaries = RestOperation('GET', '/api/v1/chat/conversations', '/chat/conversations');
  static const getConversationHistory = RestOperation('GET', '/api/v1/chat/history', '/chat/history');
  static const info_1 = RestOperation('GET', '/api/v1/node/info', '/node/info');
  static const getDevices = RestOperation('GET', '/api/v1/user/devices', '/user/devices');
  static const logoutDevice = RestOperation('DELETE', '/api/v1/user/devices/{deviceId}', '/user/devices/{deviceId}');
  static const getCurrentUserInfo = RestOperation('GET', '/api/v1/user/info', '/user/info');
  static const capabilities = RestOperation('GET', '/api/v1/chat/recovery/capabilities', '/chat/recovery/capabilities');
  static const open = RestOperation('POST', '/api/v1/chat/recovery/sessions', '/chat/recovery/sessions');
  static const snapshot = RestOperation('GET', '/api/v1/chat/recovery/sessions/{id}/snapshot', '/chat/recovery/sessions/{id}/snapshot');
  static const cut = RestOperation('POST', '/api/v1/chat/recovery/sessions/{id}/cut', '/chat/recovery/sessions/{id}/cut');
  static const mutations = RestOperation('GET', '/api/v1/chat/recovery/sessions/{id}/mutations', '/chat/recovery/sessions/{id}/mutations');
  static const ready = RestOperation('POST', '/api/v1/chat/recovery/sessions/{id}/ready', '/chat/recovery/sessions/{id}/ready');
  static const release = RestOperation('DELETE', '/api/v1/chat/recovery/sessions/{id}', '/chat/recovery/sessions/{id}');
}

const restDeviceTypes = ["android", "desktop", "ios", "web"];

class RestCapabilities {
  RestCapabilities._(this._json);
  final Map<String, dynamic> _json;
  factory RestCapabilities({
    String? capability,
    bool? legacyFullRebuildCertified,
    int? maxPageSize,
    int? pollIntervalSeconds,
    int? recordVersion,
    bool? recoveryRequiredForSafeMode,
    int? retentionSeconds,
    int? sessionTtlSeconds,
    int? staleAfterSeconds,
    List<int>? versions,
  }) => RestCapabilities.fromJson({
    'capability': ?capability,
    'legacyFullRebuildCertified': ?legacyFullRebuildCertified,
    'maxPageSize': ?maxPageSize,
    'pollIntervalSeconds': ?pollIntervalSeconds,
    'recordVersion': ?recordVersion,
    'recoveryRequiredForSafeMode': ?recoveryRequiredForSafeMode,
    'retentionSeconds': ?retentionSeconds,
    'sessionTtlSeconds': ?sessionTtlSeconds,
    'staleAfterSeconds': ?staleAfterSeconds,
    'versions': ?versions?.map((item) => item).toList(),
  });
  factory RestCapabilities.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['Capabilities'] as Map<String, dynamic>, restModelSchemas);
    return RestCapabilities._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get capability => _json['capability'] == null ? null : _json['capability'] as String;
  bool? get legacyFullRebuildCertified => _json['legacyFullRebuildCertified'] == null ? null : _json['legacyFullRebuildCertified'] as bool;
  int? get maxPageSize => _json['maxPageSize'] == null ? null : _json['maxPageSize'] as int;
  int? get pollIntervalSeconds => _json['pollIntervalSeconds'] == null ? null : _json['pollIntervalSeconds'] as int;
  int? get recordVersion => _json['recordVersion'] == null ? null : _json['recordVersion'] as int;
  bool? get recoveryRequiredForSafeMode => _json['recoveryRequiredForSafeMode'] == null ? null : _json['recoveryRequiredForSafeMode'] as bool;
  int? get retentionSeconds => _json['retentionSeconds'] == null ? null : _json['retentionSeconds'] as int;
  int? get sessionTtlSeconds => _json['sessionTtlSeconds'] == null ? null : _json['sessionTtlSeconds'] as int;
  int? get staleAfterSeconds => _json['staleAfterSeconds'] == null ? null : _json['staleAfterSeconds'] as int;
  List<int>? get versions => _json['versions'] == null ? null : (_json['versions'] as List).map((item) => item as int).toList();
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestChatMessage {
  RestChatMessage._(this._json);
  final Map<String, dynamic> _json;
  factory RestChatMessage({
    int? burnDuration,
    String? clientCreatedAt,
    String? clientMsgId,
    String? content,
    String? conversationId,
    String? createTime,
    String? filePath,
    int? fromUserId,
    int? groupId,
    int? id,
    int? isBurn,
    int? isRecalled,
    String? mentionUserIds,
    String? messageId,
    String? replyToId,
    int? senderDeviceId,
    int? sequence,
    int? status,
    int? toUserId,
    String? type,
  }) => RestChatMessage.fromJson({
    'burnDuration': ?burnDuration,
    'clientCreatedAt': ?clientCreatedAt,
    'clientMsgId': ?clientMsgId,
    'content': ?content,
    'conversationId': ?conversationId,
    'createTime': ?createTime,
    'filePath': ?filePath,
    'fromUserId': ?fromUserId,
    'groupId': ?groupId,
    'id': ?id,
    'isBurn': ?isBurn,
    'isRecalled': ?isRecalled,
    'mentionUserIds': ?mentionUserIds,
    'messageId': ?messageId,
    'replyToId': ?replyToId,
    'senderDeviceId': ?senderDeviceId,
    'sequence': ?sequence,
    'status': ?status,
    'toUserId': ?toUserId,
    'type': ?type,
  });
  factory RestChatMessage.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ChatMessage'] as Map<String, dynamic>, restModelSchemas);
    return RestChatMessage._(Map<String, dynamic>.unmodifiable(json));
  }
  int? get burnDuration => _json['burnDuration'] == null ? null : _json['burnDuration'] as int;
  String? get clientCreatedAt => _json['clientCreatedAt'] == null ? null : _json['clientCreatedAt'] as String;
  String? get clientMsgId => _json['clientMsgId'] == null ? null : _json['clientMsgId'] as String;
  String? get content => _json['content'] == null ? null : _json['content'] as String;
  String? get conversationId => _json['conversationId'] == null ? null : _json['conversationId'] as String;
  String? get createTime => _json['createTime'] == null ? null : _json['createTime'] as String;
  String? get filePath => _json['filePath'] == null ? null : _json['filePath'] as String;
  int? get fromUserId => _json['fromUserId'] == null ? null : _json['fromUserId'] as int;
  int? get groupId => _json['groupId'] == null ? null : _json['groupId'] as int;
  int? get id => _json['id'] == null ? null : _json['id'] as int;
  int? get isBurn => _json['isBurn'] == null ? null : _json['isBurn'] as int;
  int? get isRecalled => _json['isRecalled'] == null ? null : _json['isRecalled'] as int;
  String? get mentionUserIds => _json['mentionUserIds'] == null ? null : _json['mentionUserIds'] as String;
  String? get messageId => _json['messageId'] == null ? null : _json['messageId'] as String;
  String? get replyToId => _json['replyToId'] == null ? null : _json['replyToId'] as String;
  int? get senderDeviceId => _json['senderDeviceId'] == null ? null : _json['senderDeviceId'] as int;
  int? get sequence => _json['sequence'] == null ? null : _json['sequence'] as int;
  int? get status => _json['status'] == null ? null : _json['status'] as int;
  int? get toUserId => _json['toUserId'] == null ? null : _json['toUserId'] as int;
  String? get type => _json['type'] == null ? null : _json['type'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestConversationSummary {
  RestConversationSummary._(this._json);
  final Map<String, dynamic> _json;
  factory RestConversationSummary({
    String? conversationId,
    String? kind,
    String? lastMessage,
    String? lastMessageAt,
    String? lastMessageType,
    int? lastReadSequence,
    int? lastSequence,
    bool? muted,
    bool? pinned,
    int? targetId,
    int? unreadCount,
  }) => RestConversationSummary.fromJson({
    'conversationId': ?conversationId,
    'kind': ?kind,
    'lastMessage': ?lastMessage,
    'lastMessageAt': ?lastMessageAt,
    'lastMessageType': ?lastMessageType,
    'lastReadSequence': ?lastReadSequence,
    'lastSequence': ?lastSequence,
    'muted': ?muted,
    'pinned': ?pinned,
    'targetId': ?targetId,
    'unreadCount': ?unreadCount,
  });
  factory RestConversationSummary.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ConversationSummary'] as Map<String, dynamic>, restModelSchemas);
    return RestConversationSummary._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get conversationId => _json['conversationId'] == null ? null : _json['conversationId'] as String;
  String? get kind => _json['kind'] == null ? null : _json['kind'] as String;
  String? get lastMessage => _json['lastMessage'] == null ? null : _json['lastMessage'] as String;
  String? get lastMessageAt => _json['lastMessageAt'] == null ? null : _json['lastMessageAt'] as String;
  String? get lastMessageType => _json['lastMessageType'] == null ? null : _json['lastMessageType'] as String;
  int? get lastReadSequence => _json['lastReadSequence'] == null ? null : _json['lastReadSequence'] as int;
  int? get lastSequence => _json['lastSequence'] == null ? null : _json['lastSequence'] as int;
  bool? get muted => _json['muted'] == null ? null : _json['muted'] as bool;
  bool? get pinned => _json['pinned'] == null ? null : _json['pinned'] as bool;
  int? get targetId => _json['targetId'] == null ? null : _json['targetId'] as int;
  int? get unreadCount => _json['unreadCount'] == null ? null : _json['unreadCount'] as int;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestCursor {
  RestCursor._(this._json);
  final Map<String, dynamic> _json;
  factory RestCursor({
    String? position,
    String? streamEpoch,
  }) => RestCursor.fromJson({
    'position': ?position,
    'streamEpoch': ?streamEpoch,
  });
  factory RestCursor.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['Cursor'] as Map<String, dynamic>, restModelSchemas);
    return RestCursor._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get position => _json['position'] == null ? null : _json['position'] as String;
  String? get streamEpoch => _json['streamEpoch'] == null ? null : _json['streamEpoch'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestCut {
  RestCut._(this._json);
  final Map<String, dynamic> _json;
  factory RestCut({
    String? floor,
    String? streamEpoch,
    String? through,
  }) => RestCut.fromJson({
    'floor': ?floor,
    'streamEpoch': ?streamEpoch,
    'through': ?through,
  });
  factory RestCut.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['Cut'] as Map<String, dynamic>, restModelSchemas);
    return RestCut._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get floor => _json['floor'] == null ? null : _json['floor'] as String;
  String? get streamEpoch => _json['streamEpoch'] == null ? null : _json['streamEpoch'] as String;
  String? get through => _json['through'] == null ? null : _json['through'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestDeviceLoginVO {
  RestDeviceLoginVO._(this._json);
  final Map<String, dynamic> _json;
  factory RestDeviceLoginVO({
    bool? current,
    String? deviceName,
    String? deviceType,
    String? expireTime,
    int? id,
    String? loginTime,
    int? status,
    int? userId,
  }) => RestDeviceLoginVO.fromJson({
    'current': ?current,
    'deviceName': ?deviceName,
    'deviceType': ?deviceType,
    'expireTime': ?expireTime,
    'id': ?id,
    'loginTime': ?loginTime,
    'status': ?status,
    'userId': ?userId,
  });
  factory RestDeviceLoginVO.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['DeviceLoginVO'] as Map<String, dynamic>, restModelSchemas);
    return RestDeviceLoginVO._(Map<String, dynamic>.unmodifiable(json));
  }
  bool? get current => _json['current'] == null ? null : _json['current'] as bool;
  String? get deviceName => _json['deviceName'] == null ? null : _json['deviceName'] as String;
  String? get deviceType => _json['deviceType'] == null ? null : _json['deviceType'] as String;
  String? get expireTime => _json['expireTime'] == null ? null : _json['expireTime'] as String;
  int? get id => _json['id'] == null ? null : _json['id'] as int;
  String? get loginTime => _json['loginTime'] == null ? null : _json['loginTime'] as String;
  int? get status => _json['status'] == null ? null : _json['status'] as int;
  int? get userId => _json['userId'] == null ? null : _json['userId'] as int;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestItem {
  RestItem._(this._json);
  final Map<String, dynamic> _json;
  factory RestItem({
    String? accessVersion,
    String? content,
    String? conversationId,
    RestMessageDetails? details,
    String? kind,
    String? messageId,
    String? messageSequence,
    String? messageSequenceAtH,
    String? objectVersion,
    bool? readAllowed,
    bool? sendAllowed,
    String? state,
  }) => RestItem.fromJson({
    'accessVersion': ?accessVersion,
    'content': ?content,
    'conversationId': ?conversationId,
    'details': ?details?.toJson(),
    'kind': ?kind,
    'messageId': ?messageId,
    'messageSequence': ?messageSequence,
    'messageSequenceAtH': ?messageSequenceAtH,
    'objectVersion': ?objectVersion,
    'readAllowed': ?readAllowed,
    'sendAllowed': ?sendAllowed,
    'state': ?state,
  });
  factory RestItem.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['Item'] as Map<String, dynamic>, restModelSchemas);
    return RestItem._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get accessVersion => _json['accessVersion'] == null ? null : _json['accessVersion'] as String;
  String? get content => _json['content'] == null ? null : _json['content'] as String;
  String? get conversationId => _json['conversationId'] == null ? null : _json['conversationId'] as String;
  RestMessageDetails? get details => _json['details'] == null ? null : RestMessageDetails.fromJson(Map<String, dynamic>.from(_json['details'] as Map));
  String? get kind => _json['kind'] == null ? null : _json['kind'] as String;
  String? get messageId => _json['messageId'] == null ? null : _json['messageId'] as String;
  String? get messageSequence => _json['messageSequence'] == null ? null : _json['messageSequence'] as String;
  String? get messageSequenceAtH => _json['messageSequenceAtH'] == null ? null : _json['messageSequenceAtH'] as String;
  String? get objectVersion => _json['objectVersion'] == null ? null : _json['objectVersion'] as String;
  bool? get readAllowed => _json['readAllowed'] == null ? null : _json['readAllowed'] as bool;
  bool? get sendAllowed => _json['sendAllowed'] == null ? null : _json['sendAllowed'] as bool;
  String? get state => _json['state'] == null ? null : _json['state'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestLoginDTO {
  RestLoginDTO._(this._json);
  final Map<String, dynamic> _json;
  factory RestLoginDTO({
    String? deviceName,
    String? deviceType,
    required String password,
    required String username,
  }) => RestLoginDTO.fromJson({
    'deviceName': ?deviceName,
    'deviceType': ?deviceType,
    'password': password,
    'username': username,
  });
  factory RestLoginDTO.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['LoginDTO'] as Map<String, dynamic>, restModelSchemas);
    return RestLoginDTO._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get deviceName => _json['deviceName'] == null ? null : _json['deviceName'] as String;
  String? get deviceType => _json['deviceType'] == null ? null : _json['deviceType'] as String;
  String get password => _json['password'] as String;
  String get username => _json['username'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestLoginVO {
  RestLoginVO._(this._json);
  final Map<String, dynamic> _json;
  factory RestLoginVO({
    String? avatar,
    int? expiresIn,
    String? nickname,
    String? token,
    int? userId,
    String? username,
  }) => RestLoginVO.fromJson({
    'avatar': ?avatar,
    'expiresIn': ?expiresIn,
    'nickname': ?nickname,
    'token': ?token,
    'userId': ?userId,
    'username': ?username,
  });
  factory RestLoginVO.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['LoginVO'] as Map<String, dynamic>, restModelSchemas);
    return RestLoginVO._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get avatar => _json['avatar'] == null ? null : _json['avatar'] as String;
  int? get expiresIn => _json['expiresIn'] == null ? null : _json['expiresIn'] as int;
  String? get nickname => _json['nickname'] == null ? null : _json['nickname'] as String;
  String? get token => _json['token'] == null ? null : _json['token'] as String;
  int? get userId => _json['userId'] == null ? null : _json['userId'] as int;
  String? get username => _json['username'] == null ? null : _json['username'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestMessageDetails {
  RestMessageDetails._(this._json);
  final Map<String, dynamic> _json;
  factory RestMessageDetails({
    int? burnDuration,
    String? clientMsgId,
    String? contentType,
    String? createTime,
    int? fromUserId,
    int? isBurn,
    String? mentionUserIds,
    String? replyToId,
  }) => RestMessageDetails.fromJson({
    'burnDuration': ?burnDuration,
    'clientMsgId': ?clientMsgId,
    'contentType': ?contentType,
    'createTime': ?createTime,
    'fromUserId': ?fromUserId,
    'isBurn': ?isBurn,
    'mentionUserIds': ?mentionUserIds,
    'replyToId': ?replyToId,
  });
  factory RestMessageDetails.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['MessageDetails'] as Map<String, dynamic>, restModelSchemas);
    return RestMessageDetails._(Map<String, dynamic>.unmodifiable(json));
  }
  int? get burnDuration => _json['burnDuration'] == null ? null : _json['burnDuration'] as int;
  String? get clientMsgId => _json['clientMsgId'] == null ? null : _json['clientMsgId'] as String;
  String? get contentType => _json['contentType'] == null ? null : _json['contentType'] as String;
  String? get createTime => _json['createTime'] == null ? null : _json['createTime'] as String;
  int? get fromUserId => _json['fromUserId'] == null ? null : _json['fromUserId'] as int;
  int? get isBurn => _json['isBurn'] == null ? null : _json['isBurn'] as int;
  String? get mentionUserIds => _json['mentionUserIds'] == null ? null : _json['mentionUserIds'] as String;
  String? get replyToId => _json['replyToId'] == null ? null : _json['replyToId'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestMutationPage {
  RestMutationPage._(this._json);
  final Map<String, dynamic> _json;
  factory RestMutationPage({
    String? floor,
    String? fromExclusive,
    bool? hasMore,
    String? latest,
    String? nextCursor,
    List<RestRecord>? records,
    String? streamEpoch,
    String? through,
  }) => RestMutationPage.fromJson({
    'floor': ?floor,
    'fromExclusive': ?fromExclusive,
    'hasMore': ?hasMore,
    'latest': ?latest,
    'nextCursor': ?nextCursor,
    'records': ?records?.map((item) => item.toJson()).toList(),
    'streamEpoch': ?streamEpoch,
    'through': ?through,
  });
  factory RestMutationPage.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['MutationPage'] as Map<String, dynamic>, restModelSchemas);
    return RestMutationPage._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get floor => _json['floor'] == null ? null : _json['floor'] as String;
  String? get fromExclusive => _json['fromExclusive'] == null ? null : _json['fromExclusive'] as String;
  bool? get hasMore => _json['hasMore'] == null ? null : _json['hasMore'] as bool;
  String? get latest => _json['latest'] == null ? null : _json['latest'] as String;
  String? get nextCursor => _json['nextCursor'] == null ? null : _json['nextCursor'] as String;
  List<RestRecord>? get records => _json['records'] == null ? null : (_json['records'] as List).map((item) => RestRecord.fromJson(Map<String, dynamic>.from(item as Map))).toList();
  String? get streamEpoch => _json['streamEpoch'] == null ? null : _json['streamEpoch'] as String;
  String? get through => _json['through'] == null ? null : _json['through'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestNodePublicInfo {
  RestNodePublicInfo._(this._json);
  final Map<String, dynamic> _json;
  factory RestNodePublicInfo({
    String? apiBasePath,
    String? appPath,
    List<String>? capabilities,
    bool? desktopAuthSupported,
    bool? discoveryEnabled,
    String? healthPath,
    List<String>? loginMethods,
    String? mode,
    String? nodeId,
    String? nodeName,
    String? organizationName,
    int? protocolVersion,
    String? refreshTransport,
    bool? secure,
    bool? selfRegistrationEnabled,
    int? serverTime,
    String? serviceStatus,
    String? version,
    String? webSocketPath,
  }) => RestNodePublicInfo.fromJson({
    'apiBasePath': ?apiBasePath,
    'appPath': ?appPath,
    'capabilities': ?capabilities?.map((item) => item).toList(),
    'desktopAuthSupported': ?desktopAuthSupported,
    'discoveryEnabled': ?discoveryEnabled,
    'healthPath': ?healthPath,
    'loginMethods': ?loginMethods?.map((item) => item).toList(),
    'mode': ?mode,
    'nodeId': ?nodeId,
    'nodeName': ?nodeName,
    'organizationName': ?organizationName,
    'protocolVersion': ?protocolVersion,
    'refreshTransport': ?refreshTransport,
    'secure': ?secure,
    'selfRegistrationEnabled': ?selfRegistrationEnabled,
    'serverTime': ?serverTime,
    'serviceStatus': ?serviceStatus,
    'version': ?version,
    'webSocketPath': ?webSocketPath,
  });
  factory RestNodePublicInfo.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['NodePublicInfo'] as Map<String, dynamic>, restModelSchemas);
    return RestNodePublicInfo._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get apiBasePath => _json['apiBasePath'] == null ? null : _json['apiBasePath'] as String;
  String? get appPath => _json['appPath'] == null ? null : _json['appPath'] as String;
  List<String>? get capabilities => _json['capabilities'] == null ? null : (_json['capabilities'] as List).map((item) => item as String).toList();
  bool? get desktopAuthSupported => _json['desktopAuthSupported'] == null ? null : _json['desktopAuthSupported'] as bool;
  bool? get discoveryEnabled => _json['discoveryEnabled'] == null ? null : _json['discoveryEnabled'] as bool;
  String? get healthPath => _json['healthPath'] == null ? null : _json['healthPath'] as String;
  List<String>? get loginMethods => _json['loginMethods'] == null ? null : (_json['loginMethods'] as List).map((item) => item as String).toList();
  String? get mode => _json['mode'] == null ? null : _json['mode'] as String;
  String? get nodeId => _json['nodeId'] == null ? null : _json['nodeId'] as String;
  String? get nodeName => _json['nodeName'] == null ? null : _json['nodeName'] as String;
  String? get organizationName => _json['organizationName'] == null ? null : _json['organizationName'] as String;
  int? get protocolVersion => _json['protocolVersion'] == null ? null : _json['protocolVersion'] as int;
  String? get refreshTransport => _json['refreshTransport'] == null ? null : _json['refreshTransport'] as String;
  bool? get secure => _json['secure'] == null ? null : _json['secure'] as bool;
  bool? get selfRegistrationEnabled => _json['selfRegistrationEnabled'] == null ? null : _json['selfRegistrationEnabled'] as bool;
  int? get serverTime => _json['serverTime'] == null ? null : _json['serverTime'] as int;
  String? get serviceStatus => _json['serviceStatus'] == null ? null : _json['serviceStatus'] as String;
  String? get version => _json['version'] == null ? null : _json['version'] as String;
  String? get webSocketPath => _json['webSocketPath'] == null ? null : _json['webSocketPath'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestOpen {
  RestOpen._(this._json);
  final Map<String, dynamic> _json;
  factory RestOpen({
    List<String>? conversationIds,
    RestCursor? cursor,
    String? mode,
    int? protocolVersion,
  }) => RestOpen.fromJson({
    'conversationIds': ?conversationIds?.map((item) => item).toList(),
    'cursor': ?cursor?.toJson(),
    'mode': ?mode,
    'protocolVersion': ?protocolVersion,
  });
  factory RestOpen.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['Open'] as Map<String, dynamic>, restModelSchemas);
    return RestOpen._(Map<String, dynamic>.unmodifiable(json));
  }
  List<String>? get conversationIds => _json['conversationIds'] == null ? null : (_json['conversationIds'] as List).map((item) => item as String).toList();
  RestCursor? get cursor => _json['cursor'] == null ? null : RestCursor.fromJson(Map<String, dynamic>.from(_json['cursor'] as Map));
  String? get mode => _json['mode'] == null ? null : _json['mode'] as String;
  int? get protocolVersion => _json['protocolVersion'] == null ? null : _json['protocolVersion'] as int;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestReady {
  RestReady._(this._json);
  final Map<String, dynamic> _json;
  factory RestReady({
    String? acceptedCursor,
    String? latest,
    bool? ready,
    String? streamEpoch,
  }) => RestReady.fromJson({
    'acceptedCursor': ?acceptedCursor,
    'latest': ?latest,
    'ready': ?ready,
    'streamEpoch': ?streamEpoch,
  });
  factory RestReady.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['Ready'] as Map<String, dynamic>, restModelSchemas);
    return RestReady._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get acceptedCursor => _json['acceptedCursor'] == null ? null : _json['acceptedCursor'] as String;
  String? get latest => _json['latest'] == null ? null : _json['latest'] as String;
  bool? get ready => _json['ready'] == null ? null : _json['ready'] as bool;
  String? get streamEpoch => _json['streamEpoch'] == null ? null : _json['streamEpoch'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestReadyRequest {
  RestReadyRequest._(this._json);
  final Map<String, dynamic> _json;
  factory RestReadyRequest({
    String? appliedCursor,
    bool? snapshotComplete,
  }) => RestReadyRequest.fromJson({
    'appliedCursor': ?appliedCursor,
    'snapshotComplete': ?snapshotComplete,
  });
  factory RestReadyRequest.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ReadyRequest'] as Map<String, dynamic>, restModelSchemas);
    return RestReadyRequest._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get appliedCursor => _json['appliedCursor'] == null ? null : _json['appliedCursor'] as String;
  bool? get snapshotComplete => _json['snapshotComplete'] == null ? null : _json['snapshotComplete'] as bool;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestRecord {
  RestRecord._(this._json);
  final Map<String, dynamic> _json;
  factory RestRecord({
    String? accessVersion,
    String? committedAt,
    String? conversationId,
    String? cursor,
    String? eventId,
    String? messageId,
    String? objectVersion,
    bool? readAllowed,
    String? reason,
    bool? rebuildConversation,
    int? recordVersion,
    bool? sendAllowed,
    String? streamEpoch,
    String? type,
  }) => RestRecord.fromJson({
    'accessVersion': ?accessVersion,
    'committedAt': ?committedAt,
    'conversationId': ?conversationId,
    'cursor': ?cursor,
    'eventId': ?eventId,
    'messageId': ?messageId,
    'objectVersion': ?objectVersion,
    'readAllowed': ?readAllowed,
    'reason': ?reason,
    'rebuildConversation': ?rebuildConversation,
    'recordVersion': ?recordVersion,
    'sendAllowed': ?sendAllowed,
    'streamEpoch': ?streamEpoch,
    'type': ?type,
  });
  factory RestRecord.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['Record'] as Map<String, dynamic>, restModelSchemas);
    return RestRecord._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get accessVersion => _json['accessVersion'] == null ? null : _json['accessVersion'] as String;
  String? get committedAt => _json['committedAt'] == null ? null : _json['committedAt'] as String;
  String? get conversationId => _json['conversationId'] == null ? null : _json['conversationId'] as String;
  String? get cursor => _json['cursor'] == null ? null : _json['cursor'] as String;
  String? get eventId => _json['eventId'] == null ? null : _json['eventId'] as String;
  String? get messageId => _json['messageId'] == null ? null : _json['messageId'] as String;
  String? get objectVersion => _json['objectVersion'] == null ? null : _json['objectVersion'] as String;
  bool? get readAllowed => _json['readAllowed'] == null ? null : _json['readAllowed'] as bool;
  String? get reason => _json['reason'] == null ? null : _json['reason'] as String;
  bool? get rebuildConversation => _json['rebuildConversation'] == null ? null : _json['rebuildConversation'] as bool;
  int? get recordVersion => _json['recordVersion'] == null ? null : _json['recordVersion'] as int;
  bool? get sendAllowed => _json['sendAllowed'] == null ? null : _json['sendAllowed'] as bool;
  String? get streamEpoch => _json['streamEpoch'] == null ? null : _json['streamEpoch'] as String;
  String? get type => _json['type'] == null ? null : _json['type'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestRegisterDTO {
  RestRegisterDTO._(this._json);
  final Map<String, dynamic> _json;
  factory RestRegisterDTO({
    String? nickname,
    required String password,
    required String username,
  }) => RestRegisterDTO.fromJson({
    'nickname': ?nickname,
    'password': password,
    'username': username,
  });
  factory RestRegisterDTO.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['RegisterDTO'] as Map<String, dynamic>, restModelSchemas);
    return RestRegisterDTO._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get nickname => _json['nickname'] == null ? null : _json['nickname'] as String;
  String get password => _json['password'] as String;
  String get username => _json['username'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestResultCapabilities {
  RestResultCapabilities._(this._json);
  final Map<String, dynamic> _json;
  factory RestResultCapabilities({
    required int code,
    RestCapabilities? data,
    required String msg,
    String? requestId,
  }) => RestResultCapabilities.fromJson({
    'code': code,
    'data': ?data?.toJson(),
    'msg': msg,
    'requestId': ?requestId,
  });
  factory RestResultCapabilities.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ResultCapabilities'] as Map<String, dynamic>, restModelSchemas);
    return RestResultCapabilities._(Map<String, dynamic>.unmodifiable(json));
  }
  int get code => _json['code'] as int;
  RestCapabilities? get data => _json['data'] == null ? null : RestCapabilities.fromJson(Map<String, dynamic>.from(_json['data'] as Map));
  String get msg => _json['msg'] as String;
  String? get requestId => _json['requestId'] == null ? null : _json['requestId'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestResultCut {
  RestResultCut._(this._json);
  final Map<String, dynamic> _json;
  factory RestResultCut({
    required int code,
    RestCut? data,
    required String msg,
    String? requestId,
  }) => RestResultCut.fromJson({
    'code': code,
    'data': ?data?.toJson(),
    'msg': msg,
    'requestId': ?requestId,
  });
  factory RestResultCut.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ResultCut'] as Map<String, dynamic>, restModelSchemas);
    return RestResultCut._(Map<String, dynamic>.unmodifiable(json));
  }
  int get code => _json['code'] as int;
  RestCut? get data => _json['data'] == null ? null : RestCut.fromJson(Map<String, dynamic>.from(_json['data'] as Map));
  String get msg => _json['msg'] as String;
  String? get requestId => _json['requestId'] == null ? null : _json['requestId'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestResultError {
  RestResultError._(this._json);
  final Map<String, dynamic> _json;
  factory RestResultError({
    required int code,
    Map<String, dynamic>? data,
    required String msg,
    String? requestId,
  }) => RestResultError.fromJson({
    'code': code,
    'data': ?data,
    'msg': msg,
    'requestId': ?requestId,
  });
  factory RestResultError.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ResultError'] as Map<String, dynamic>, restModelSchemas);
    return RestResultError._(Map<String, dynamic>.unmodifiable(json));
  }
  int get code => _json['code'] as int;
  Map<String, dynamic>? get data => _json['data'] == null ? null : Map<String, dynamic>.from(_json['data'] as Map);
  String get msg => _json['msg'] as String;
  String? get requestId => _json['requestId'] == null ? null : _json['requestId'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestResultListChatMessage {
  RestResultListChatMessage._(this._json);
  final Map<String, dynamic> _json;
  factory RestResultListChatMessage({
    required int code,
    List<RestChatMessage>? data,
    required String msg,
    String? requestId,
  }) => RestResultListChatMessage.fromJson({
    'code': code,
    'data': ?data?.map((item) => item.toJson()).toList(),
    'msg': msg,
    'requestId': ?requestId,
  });
  factory RestResultListChatMessage.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ResultListChatMessage'] as Map<String, dynamic>, restModelSchemas);
    return RestResultListChatMessage._(Map<String, dynamic>.unmodifiable(json));
  }
  int get code => _json['code'] as int;
  List<RestChatMessage>? get data => _json['data'] == null ? null : (_json['data'] as List).map((item) => RestChatMessage.fromJson(Map<String, dynamic>.from(item as Map))).toList();
  String get msg => _json['msg'] as String;
  String? get requestId => _json['requestId'] == null ? null : _json['requestId'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestResultListConversationSummary {
  RestResultListConversationSummary._(this._json);
  final Map<String, dynamic> _json;
  factory RestResultListConversationSummary({
    required int code,
    List<RestConversationSummary>? data,
    required String msg,
    String? requestId,
  }) => RestResultListConversationSummary.fromJson({
    'code': code,
    'data': ?data?.map((item) => item.toJson()).toList(),
    'msg': msg,
    'requestId': ?requestId,
  });
  factory RestResultListConversationSummary.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ResultListConversationSummary'] as Map<String, dynamic>, restModelSchemas);
    return RestResultListConversationSummary._(Map<String, dynamic>.unmodifiable(json));
  }
  int get code => _json['code'] as int;
  List<RestConversationSummary>? get data => _json['data'] == null ? null : (_json['data'] as List).map((item) => RestConversationSummary.fromJson(Map<String, dynamic>.from(item as Map))).toList();
  String get msg => _json['msg'] as String;
  String? get requestId => _json['requestId'] == null ? null : _json['requestId'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestResultListDeviceLoginVO {
  RestResultListDeviceLoginVO._(this._json);
  final Map<String, dynamic> _json;
  factory RestResultListDeviceLoginVO({
    required int code,
    List<RestDeviceLoginVO>? data,
    required String msg,
    String? requestId,
  }) => RestResultListDeviceLoginVO.fromJson({
    'code': code,
    'data': ?data?.map((item) => item.toJson()).toList(),
    'msg': msg,
    'requestId': ?requestId,
  });
  factory RestResultListDeviceLoginVO.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ResultListDeviceLoginVO'] as Map<String, dynamic>, restModelSchemas);
    return RestResultListDeviceLoginVO._(Map<String, dynamic>.unmodifiable(json));
  }
  int get code => _json['code'] as int;
  List<RestDeviceLoginVO>? get data => _json['data'] == null ? null : (_json['data'] as List).map((item) => RestDeviceLoginVO.fromJson(Map<String, dynamic>.from(item as Map))).toList();
  String get msg => _json['msg'] as String;
  String? get requestId => _json['requestId'] == null ? null : _json['requestId'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestResultLoginVO {
  RestResultLoginVO._(this._json);
  final Map<String, dynamic> _json;
  factory RestResultLoginVO({
    required int code,
    RestLoginVO? data,
    required String msg,
    String? requestId,
  }) => RestResultLoginVO.fromJson({
    'code': code,
    'data': ?data?.toJson(),
    'msg': msg,
    'requestId': ?requestId,
  });
  factory RestResultLoginVO.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ResultLoginVO'] as Map<String, dynamic>, restModelSchemas);
    return RestResultLoginVO._(Map<String, dynamic>.unmodifiable(json));
  }
  int get code => _json['code'] as int;
  RestLoginVO? get data => _json['data'] == null ? null : RestLoginVO.fromJson(Map<String, dynamic>.from(_json['data'] as Map));
  String get msg => _json['msg'] as String;
  String? get requestId => _json['requestId'] == null ? null : _json['requestId'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestResultMutationPage {
  RestResultMutationPage._(this._json);
  final Map<String, dynamic> _json;
  factory RestResultMutationPage({
    required int code,
    RestMutationPage? data,
    required String msg,
    String? requestId,
  }) => RestResultMutationPage.fromJson({
    'code': code,
    'data': ?data?.toJson(),
    'msg': msg,
    'requestId': ?requestId,
  });
  factory RestResultMutationPage.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ResultMutationPage'] as Map<String, dynamic>, restModelSchemas);
    return RestResultMutationPage._(Map<String, dynamic>.unmodifiable(json));
  }
  int get code => _json['code'] as int;
  RestMutationPage? get data => _json['data'] == null ? null : RestMutationPage.fromJson(Map<String, dynamic>.from(_json['data'] as Map));
  String get msg => _json['msg'] as String;
  String? get requestId => _json['requestId'] == null ? null : _json['requestId'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestResultNodePublicInfo {
  RestResultNodePublicInfo._(this._json);
  final Map<String, dynamic> _json;
  factory RestResultNodePublicInfo({
    required int code,
    RestNodePublicInfo? data,
    required String msg,
    String? requestId,
  }) => RestResultNodePublicInfo.fromJson({
    'code': code,
    'data': ?data?.toJson(),
    'msg': msg,
    'requestId': ?requestId,
  });
  factory RestResultNodePublicInfo.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ResultNodePublicInfo'] as Map<String, dynamic>, restModelSchemas);
    return RestResultNodePublicInfo._(Map<String, dynamic>.unmodifiable(json));
  }
  int get code => _json['code'] as int;
  RestNodePublicInfo? get data => _json['data'] == null ? null : RestNodePublicInfo.fromJson(Map<String, dynamic>.from(_json['data'] as Map));
  String get msg => _json['msg'] as String;
  String? get requestId => _json['requestId'] == null ? null : _json['requestId'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestResultReady {
  RestResultReady._(this._json);
  final Map<String, dynamic> _json;
  factory RestResultReady({
    required int code,
    RestReady? data,
    required String msg,
    String? requestId,
  }) => RestResultReady.fromJson({
    'code': code,
    'data': ?data?.toJson(),
    'msg': msg,
    'requestId': ?requestId,
  });
  factory RestResultReady.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ResultReady'] as Map<String, dynamic>, restModelSchemas);
    return RestResultReady._(Map<String, dynamic>.unmodifiable(json));
  }
  int get code => _json['code'] as int;
  RestReady? get data => _json['data'] == null ? null : RestReady.fromJson(Map<String, dynamic>.from(_json['data'] as Map));
  String get msg => _json['msg'] as String;
  String? get requestId => _json['requestId'] == null ? null : _json['requestId'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestResultSessionResponse {
  RestResultSessionResponse._(this._json);
  final Map<String, dynamic> _json;
  factory RestResultSessionResponse({
    required int code,
    RestSessionResponse? data,
    required String msg,
    String? requestId,
  }) => RestResultSessionResponse.fromJson({
    'code': code,
    'data': ?data?.toJson(),
    'msg': msg,
    'requestId': ?requestId,
  });
  factory RestResultSessionResponse.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ResultSessionResponse'] as Map<String, dynamic>, restModelSchemas);
    return RestResultSessionResponse._(Map<String, dynamic>.unmodifiable(json));
  }
  int get code => _json['code'] as int;
  RestSessionResponse? get data => _json['data'] == null ? null : RestSessionResponse.fromJson(Map<String, dynamic>.from(_json['data'] as Map));
  String get msg => _json['msg'] as String;
  String? get requestId => _json['requestId'] == null ? null : _json['requestId'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestResultSnapshotPage {
  RestResultSnapshotPage._(this._json);
  final Map<String, dynamic> _json;
  factory RestResultSnapshotPage({
    required int code,
    RestSnapshotPage? data,
    required String msg,
    String? requestId,
  }) => RestResultSnapshotPage.fromJson({
    'code': code,
    'data': ?data?.toJson(),
    'msg': msg,
    'requestId': ?requestId,
  });
  factory RestResultSnapshotPage.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ResultSnapshotPage'] as Map<String, dynamic>, restModelSchemas);
    return RestResultSnapshotPage._(Map<String, dynamic>.unmodifiable(json));
  }
  int get code => _json['code'] as int;
  RestSnapshotPage? get data => _json['data'] == null ? null : RestSnapshotPage.fromJson(Map<String, dynamic>.from(_json['data'] as Map));
  String get msg => _json['msg'] as String;
  String? get requestId => _json['requestId'] == null ? null : _json['requestId'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestResultUser {
  RestResultUser._(this._json);
  final Map<String, dynamic> _json;
  factory RestResultUser({
    required int code,
    RestUser? data,
    required String msg,
    String? requestId,
  }) => RestResultUser.fromJson({
    'code': code,
    'data': ?data?.toJson(),
    'msg': msg,
    'requestId': ?requestId,
  });
  factory RestResultUser.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ResultUser'] as Map<String, dynamic>, restModelSchemas);
    return RestResultUser._(Map<String, dynamic>.unmodifiable(json));
  }
  int get code => _json['code'] as int;
  RestUser? get data => _json['data'] == null ? null : RestUser.fromJson(Map<String, dynamic>.from(_json['data'] as Map));
  String get msg => _json['msg'] as String;
  String? get requestId => _json['requestId'] == null ? null : _json['requestId'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestResultVoid {
  RestResultVoid._(this._json);
  final Map<String, dynamic> _json;
  factory RestResultVoid({
    required int code,
    Map<String, dynamic>? data,
    required String msg,
    String? requestId,
  }) => RestResultVoid.fromJson({
    'code': code,
    'data': ?data,
    'msg': msg,
    'requestId': ?requestId,
  });
  factory RestResultVoid.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['ResultVoid'] as Map<String, dynamic>, restModelSchemas);
    return RestResultVoid._(Map<String, dynamic>.unmodifiable(json));
  }
  int get code => _json['code'] as int;
  Map<String, dynamic>? get data => _json['data'] == null ? null : Map<String, dynamic>.from(_json['data'] as Map);
  String get msg => _json['msg'] as String;
  String? get requestId => _json['requestId'] == null ? null : _json['requestId'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestSessionResponse {
  RestSessionResponse._(this._json);
  final Map<String, dynamic> _json;
  factory RestSessionResponse({
    String? expiresAt,
    String? floor,
    String? latest,
    String? mode,
    String? recoveryId,
    String? snapshotBoundary,
    String? snapshotId,
    String? startCursor,
    String? streamEpoch,
  }) => RestSessionResponse.fromJson({
    'expiresAt': ?expiresAt,
    'floor': ?floor,
    'latest': ?latest,
    'mode': ?mode,
    'recoveryId': ?recoveryId,
    'snapshotBoundary': ?snapshotBoundary,
    'snapshotId': ?snapshotId,
    'startCursor': ?startCursor,
    'streamEpoch': ?streamEpoch,
  });
  factory RestSessionResponse.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['SessionResponse'] as Map<String, dynamic>, restModelSchemas);
    return RestSessionResponse._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get expiresAt => _json['expiresAt'] == null ? null : _json['expiresAt'] as String;
  String? get floor => _json['floor'] == null ? null : _json['floor'] as String;
  String? get latest => _json['latest'] == null ? null : _json['latest'] as String;
  String? get mode => _json['mode'] == null ? null : _json['mode'] as String;
  String? get recoveryId => _json['recoveryId'] == null ? null : _json['recoveryId'] as String;
  String? get snapshotBoundary => _json['snapshotBoundary'] == null ? null : _json['snapshotBoundary'] as String;
  String? get snapshotId => _json['snapshotId'] == null ? null : _json['snapshotId'] as String;
  String? get startCursor => _json['startCursor'] == null ? null : _json['startCursor'] as String;
  String? get streamEpoch => _json['streamEpoch'] == null ? null : _json['streamEpoch'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestSnapshotPage {
  RestSnapshotPage._(this._json);
  final Map<String, dynamic> _json;
  factory RestSnapshotPage({
    String? boundary,
    List<RestItem>? items,
    String? nextPageToken,
    bool? snapshotComplete,
    String? snapshotId,
  }) => RestSnapshotPage.fromJson({
    'boundary': ?boundary,
    'items': ?items?.map((item) => item.toJson()).toList(),
    'nextPageToken': ?nextPageToken,
    'snapshotComplete': ?snapshotComplete,
    'snapshotId': ?snapshotId,
  });
  factory RestSnapshotPage.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['SnapshotPage'] as Map<String, dynamic>, restModelSchemas);
    return RestSnapshotPage._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get boundary => _json['boundary'] == null ? null : _json['boundary'] as String;
  List<RestItem>? get items => _json['items'] == null ? null : (_json['items'] as List).map((item) => RestItem.fromJson(Map<String, dynamic>.from(item as Map))).toList();
  String? get nextPageToken => _json['nextPageToken'] == null ? null : _json['nextPageToken'] as String;
  bool? get snapshotComplete => _json['snapshotComplete'] == null ? null : _json['snapshotComplete'] as bool;
  String? get snapshotId => _json['snapshotId'] == null ? null : _json['snapshotId'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestTokenRefreshDTO {
  RestTokenRefreshDTO._(this._json);
  final Map<String, dynamic> _json;
  factory RestTokenRefreshDTO({
    String? deviceName,
    String? deviceType,
    String? refreshToken,
  }) => RestTokenRefreshDTO.fromJson({
    'deviceName': ?deviceName,
    'deviceType': ?deviceType,
    'refreshToken': ?refreshToken,
  });
  factory RestTokenRefreshDTO.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['TokenRefreshDTO'] as Map<String, dynamic>, restModelSchemas);
    return RestTokenRefreshDTO._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get deviceName => _json['deviceName'] == null ? null : _json['deviceName'] as String;
  String? get deviceType => _json['deviceType'] == null ? null : _json['deviceType'] as String;
  String? get refreshToken => _json['refreshToken'] == null ? null : _json['refreshToken'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

class RestUser {
  RestUser._(this._json);
  final Map<String, dynamic> _json;
  factory RestUser({
    String? archiveReason,
    String? archivedAt,
    int? archivedBy,
    String? avatar,
    int? canSendBroadcast,
    String? createTime,
    String? deviceType,
    int? id,
    String? lastLoginAt,
    String? muteEnd,
    String? muteStart,
    String? nickname,
    int? online,
    String? signature,
    int? status,
    String? updateTime,
    String? username,
  }) => RestUser.fromJson({
    'archiveReason': ?archiveReason,
    'archivedAt': ?archivedAt,
    'archivedBy': ?archivedBy,
    'avatar': ?avatar,
    'canSendBroadcast': ?canSendBroadcast,
    'createTime': ?createTime,
    'deviceType': ?deviceType,
    'id': ?id,
    'lastLoginAt': ?lastLoginAt,
    'muteEnd': ?muteEnd,
    'muteStart': ?muteStart,
    'nickname': ?nickname,
    'online': ?online,
    'signature': ?signature,
    'status': ?status,
    'updateTime': ?updateTime,
    'username': ?username,
  });
  factory RestUser.fromJson(Map<String, dynamic> json) {
    validateWire(json, restModelSchemas['User'] as Map<String, dynamic>, restModelSchemas);
    return RestUser._(Map<String, dynamic>.unmodifiable(json));
  }
  String? get archiveReason => _json['archiveReason'] == null ? null : _json['archiveReason'] as String;
  String? get archivedAt => _json['archivedAt'] == null ? null : _json['archivedAt'] as String;
  int? get archivedBy => _json['archivedBy'] == null ? null : _json['archivedBy'] as int;
  String? get avatar => _json['avatar'] == null ? null : _json['avatar'] as String;
  int? get canSendBroadcast => _json['canSendBroadcast'] == null ? null : _json['canSendBroadcast'] as int;
  String? get createTime => _json['createTime'] == null ? null : _json['createTime'] as String;
  String? get deviceType => _json['deviceType'] == null ? null : _json['deviceType'] as String;
  int? get id => _json['id'] == null ? null : _json['id'] as int;
  String? get lastLoginAt => _json['lastLoginAt'] == null ? null : _json['lastLoginAt'] as String;
  String? get muteEnd => _json['muteEnd'] == null ? null : _json['muteEnd'] as String;
  String? get muteStart => _json['muteStart'] == null ? null : _json['muteStart'] as String;
  String? get nickname => _json['nickname'] == null ? null : _json['nickname'] as String;
  int? get online => _json['online'] == null ? null : _json['online'] as int;
  String? get signature => _json['signature'] == null ? null : _json['signature'] as String;
  int? get status => _json['status'] == null ? null : _json['status'] as int;
  String? get updateTime => _json['updateTime'] == null ? null : _json['updateTime'] as String;
  String? get username => _json['username'] == null ? null : _json['username'] as String;
  // Preserve absent vs explicit null and unknown forward-compatible fields.
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);
}

const Map<String, dynamic> restModelSchemas = {
  "Capabilities": {
    "properties": {
      "capability": {
        "type": "string"
      },
      "legacyFullRebuildCertified": {
        "type": "boolean"
      },
      "maxPageSize": {
        "format": "int32",
        "type": "integer"
      },
      "pollIntervalSeconds": {
        "format": "int32",
        "type": "integer"
      },
      "recordVersion": {
        "format": "int32",
        "type": "integer"
      },
      "recoveryRequiredForSafeMode": {
        "type": "boolean"
      },
      "retentionSeconds": {
        "format": "int32",
        "type": "integer"
      },
      "sessionTtlSeconds": {
        "format": "int32",
        "type": "integer"
      },
      "staleAfterSeconds": {
        "format": "int32",
        "type": "integer"
      },
      "versions": {
        "items": {
          "format": "int32",
          "type": "integer"
        },
        "type": "array"
      }
    },
    "type": "object"
  },
  "ChatMessage": {
    "properties": {
      "burnDuration": {
        "format": "int32",
        "nullable": true,
        "type": "integer"
      },
      "clientCreatedAt": {
        "format": "date-time",
        "nullable": true,
        "type": "string"
      },
      "clientMsgId": {
        "nullable": true,
        "type": "string"
      },
      "content": {
        "nullable": true,
        "type": "string"
      },
      "conversationId": {
        "nullable": true,
        "type": "string"
      },
      "createTime": {
        "format": "date-time",
        "nullable": true,
        "type": "string"
      },
      "filePath": {
        "nullable": true,
        "type": "string"
      },
      "fromUserId": {
        "format": "int64",
        "nullable": true,
        "type": "integer"
      },
      "groupId": {
        "format": "int64",
        "nullable": true,
        "type": "integer"
      },
      "id": {
        "format": "int64",
        "nullable": true,
        "type": "integer"
      },
      "isBurn": {
        "format": "int32",
        "nullable": true,
        "type": "integer"
      },
      "isRecalled": {
        "format": "int32",
        "nullable": true,
        "type": "integer"
      },
      "mentionUserIds": {
        "nullable": true,
        "type": "string"
      },
      "messageId": {
        "nullable": true,
        "type": "string"
      },
      "replyToId": {
        "nullable": true,
        "type": "string"
      },
      "senderDeviceId": {
        "format": "int64",
        "nullable": true,
        "type": "integer"
      },
      "sequence": {
        "format": "int64",
        "nullable": true,
        "type": "integer"
      },
      "status": {
        "format": "int32",
        "nullable": true,
        "type": "integer"
      },
      "toUserId": {
        "format": "int64",
        "nullable": true,
        "type": "integer"
      },
      "type": {
        "nullable": true,
        "type": "string"
      }
    },
    "type": "object",
    "x-java-source": "com.lanchat.entity.ChatMessage",
    "x-nullability-policy": "Java reference fields may be null; absence remains separate from business requiredness."
  },
  "ConversationSummary": {
    "properties": {
      "conversationId": {
        "nullable": true,
        "type": "string"
      },
      "kind": {
        "nullable": true,
        "type": "string"
      },
      "lastMessage": {
        "nullable": true,
        "type": "string"
      },
      "lastMessageAt": {
        "format": "date-time",
        "nullable": true,
        "type": "string"
      },
      "lastMessageType": {
        "nullable": true,
        "type": "string"
      },
      "lastReadSequence": {
        "format": "int64",
        "nullable": true,
        "type": "integer"
      },
      "lastSequence": {
        "format": "int64",
        "nullable": true,
        "type": "integer"
      },
      "muted": {
        "nullable": true,
        "type": "boolean"
      },
      "pinned": {
        "nullable": true,
        "type": "boolean"
      },
      "targetId": {
        "format": "int64",
        "nullable": true,
        "type": "integer"
      },
      "unreadCount": {
        "format": "int64",
        "nullable": true,
        "type": "integer"
      }
    },
    "type": "object",
    "x-java-source": "com.lanchat.dto.ConversationSummary",
    "x-nullability-policy": "Java reference fields may be null; absence remains separate from business requiredness."
  },
  "Cursor": {
    "properties": {
      "position": {
        "type": "string"
      },
      "streamEpoch": {
        "type": "string"
      }
    },
    "type": "object"
  },
  "Cut": {
    "properties": {
      "floor": {
        "type": "string"
      },
      "streamEpoch": {
        "type": "string"
      },
      "through": {
        "type": "string"
      }
    },
    "type": "object"
  },
  "DeviceLoginVO": {
    "properties": {
      "current": {
        "type": "boolean"
      },
      "deviceName": {
        "nullable": true,
        "type": "string"
      },
      "deviceType": {
        "nullable": true,
        "type": "string"
      },
      "expireTime": {
        "format": "date-time",
        "nullable": true,
        "type": "string"
      },
      "id": {
        "format": "int64",
        "nullable": true,
        "type": "integer"
      },
      "loginTime": {
        "format": "date-time",
        "nullable": true,
        "type": "string"
      },
      "status": {
        "format": "int32",
        "nullable": true,
        "type": "integer"
      },
      "userId": {
        "format": "int64",
        "nullable": true,
        "type": "integer"
      }
    },
    "type": "object",
    "x-java-source": "com.lanchat.dto.DeviceLoginVO",
    "x-nullability-policy": "Java reference fields may be null; absence remains separate from business requiredness."
  },
  "Item": {
    "properties": {
      "accessVersion": {
        "type": "string"
      },
      "content": {
        "type": "string"
      },
      "conversationId": {
        "type": "string"
      },
      "details": {
        "\$ref": "#/components/schemas/MessageDetails"
      },
      "kind": {
        "type": "string"
      },
      "messageId": {
        "type": "string"
      },
      "messageSequence": {
        "type": "string"
      },
      "messageSequenceAtH": {
        "type": "string"
      },
      "objectVersion": {
        "type": "string"
      },
      "readAllowed": {
        "type": "boolean"
      },
      "sendAllowed": {
        "type": "boolean"
      },
      "state": {
        "type": "string"
      }
    },
    "type": "object"
  },
  "LoginDTO": {
    "properties": {
      "deviceName": {
        "nullable": true,
        "type": "string"
      },
      "deviceType": {
        "description": "Trim/lowercase; missing, blank or unknown input normalizes to web. This is not a rejecting enum.",
        "nullable": true,
        "type": "string",
        "x-normalized-values": [
          "android",
          "desktop",
          "ios",
          "web"
        ]
      },
      "password": {
        "description": "Required non-blank value; normalization, reserved names and password policy remain in UserServiceImpl and behavior tests.",
        "minLength": 1,
        "type": "string"
      },
      "username": {
        "description": "Required non-blank value; normalization, reserved names and password policy remain in UserServiceImpl and behavior tests.",
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "username",
      "password"
    ],
    "type": "object",
    "x-java-source": "com.lanchat.dto.LoginDTO",
    "x-nullability-policy": "Java reference fields may be null; absence remains separate from business requiredness."
  },
  "LoginVO": {
    "properties": {
      "avatar": {
        "nullable": true,
        "type": "string"
      },
      "expiresIn": {
        "format": "int64",
        "nullable": true,
        "type": "integer"
      },
      "nickname": {
        "nullable": true,
        "type": "string"
      },
      "token": {
        "nullable": true,
        "type": "string"
      },
      "userId": {
        "format": "int64",
        "nullable": true,
        "type": "integer"
      },
      "username": {
        "nullable": true,
        "type": "string"
      }
    },
    "type": "object",
    "x-java-source": "com.lanchat.dto.LoginVO",
    "x-nullability-policy": "Java reference fields may be null; absence remains separate from business requiredness."
  },
  "MessageDetails": {
    "properties": {
      "burnDuration": {
        "format": "int32",
        "type": "integer"
      },
      "clientMsgId": {
        "type": "string"
      },
      "contentType": {
        "type": "string"
      },
      "createTime": {
        "format": "date-time",
        "type": "string"
      },
      "fromUserId": {
        "format": "int64",
        "type": "integer"
      },
      "isBurn": {
        "format": "int32",
        "type": "integer"
      },
      "mentionUserIds": {
        "type": "string"
      },
      "replyToId": {
        "type": "string"
      }
    },
    "type": "object"
  },
  "MutationPage": {
    "properties": {
      "floor": {
        "type": "string"
      },
      "fromExclusive": {
        "type": "string"
      },
      "hasMore": {
        "type": "boolean"
      },
      "latest": {
        "type": "string"
      },
      "nextCursor": {
        "type": "string"
      },
      "records": {
        "items": {
          "\$ref": "#/components/schemas/Record"
        },
        "type": "array"
      },
      "streamEpoch": {
        "type": "string"
      },
      "through": {
        "type": "string"
      }
    },
    "type": "object"
  },
  "NodePublicInfo": {
    "properties": {
      "apiBasePath": {
        "nullable": true,
        "type": "string"
      },
      "appPath": {
        "nullable": true,
        "type": "string"
      },
      "capabilities": {
        "items": {
          "type": "string"
        },
        "nullable": true,
        "type": "array",
        "uniqueItems": true
      },
      "desktopAuthSupported": {
        "type": "boolean"
      },
      "discoveryEnabled": {
        "type": "boolean"
      },
      "healthPath": {
        "nullable": true,
        "type": "string"
      },
      "loginMethods": {
        "items": {
          "type": "string"
        },
        "nullable": true,
        "type": "array",
        "uniqueItems": true
      },
      "mode": {
        "nullable": true,
        "type": "string"
      },
      "nodeId": {
        "nullable": true,
        "type": "string"
      },
      "nodeName": {
        "nullable": true,
        "type": "string"
      },
      "organizationName": {
        "nullable": true,
        "type": "string"
      },
      "protocolVersion": {
        "format": "int32",
        "type": "integer"
      },
      "refreshTransport": {
        "nullable": true,
        "type": "string"
      },
      "secure": {
        "type": "boolean"
      },
      "selfRegistrationEnabled": {
        "type": "boolean"
      },
      "serverTime": {
        "format": "int64",
        "type": "integer"
      },
      "serviceStatus": {
        "nullable": true,
        "type": "string"
      },
      "version": {
        "nullable": true,
        "type": "string"
      },
      "webSocketPath": {
        "nullable": true,
        "type": "string"
      }
    },
    "type": "object",
    "x-java-source": "com.lanchat.dto.NodePublicInfo",
    "x-nullability-policy": "Java reference fields may be null; absence remains separate from business requiredness."
  },
  "Open": {
    "properties": {
      "conversationIds": {
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "cursor": {
        "\$ref": "#/components/schemas/Cursor"
      },
      "mode": {
        "type": "string"
      },
      "protocolVersion": {
        "format": "int32",
        "type": "integer"
      }
    },
    "type": "object"
  },
  "Ready": {
    "properties": {
      "acceptedCursor": {
        "type": "string"
      },
      "latest": {
        "type": "string"
      },
      "ready": {
        "type": "boolean"
      },
      "streamEpoch": {
        "type": "string"
      }
    },
    "type": "object"
  },
  "ReadyRequest": {
    "properties": {
      "appliedCursor": {
        "type": "string"
      },
      "snapshotComplete": {
        "type": "boolean"
      }
    },
    "type": "object"
  },
  "Record": {
    "properties": {
      "accessVersion": {
        "type": "string"
      },
      "committedAt": {
        "type": "string"
      },
      "conversationId": {
        "type": "string"
      },
      "cursor": {
        "type": "string"
      },
      "eventId": {
        "type": "string"
      },
      "messageId": {
        "type": "string"
      },
      "objectVersion": {
        "type": "string"
      },
      "readAllowed": {
        "type": "boolean"
      },
      "reason": {
        "enum": [
          "REMOVED",
          "GROUP_REMOVED",
          "DESTROYED",
          "ACCESS_REVOKED",
          "FRIEND_DELETED",
          "SEND_DENIED",
          "GRANTED",
          "UPDATED"
        ],
        "type": "string"
      },
      "rebuildConversation": {
        "type": "boolean"
      },
      "recordVersion": {
        "format": "int32",
        "type": "integer"
      },
      "sendAllowed": {
        "type": "boolean"
      },
      "streamEpoch": {
        "type": "string"
      },
      "type": {
        "enum": [
          "MESSAGE_RECALLED",
          "MESSAGE_BURNED",
          "MESSAGE_UNAVAILABLE",
          "CONVERSATION_ACCESS_REVOKED",
          "CONVERSATION_ACCESS_CHANGED"
        ],
        "type": "string"
      }
    },
    "type": "object"
  },
  "RegisterDTO": {
    "properties": {
      "nickname": {
        "nullable": true,
        "type": "string"
      },
      "password": {
        "description": "Required non-blank value; normalization, reserved names and password policy remain in UserServiceImpl and behavior tests.",
        "minLength": 1,
        "type": "string"
      },
      "username": {
        "description": "Required non-blank value; normalization, reserved names and password policy remain in UserServiceImpl and behavior tests.",
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "username",
      "password"
    ],
    "type": "object",
    "x-java-source": "com.lanchat.dto.RegisterDTO",
    "x-nullability-policy": "Java reference fields may be null; absence remains separate from business requiredness."
  },
  "ResultCapabilities": {
    "properties": {
      "code": {
        "format": "int32",
        "type": "integer"
      },
      "data": {
        "anyOf": [
          {
            "\$ref": "#/components/schemas/Capabilities"
          },
          {
            "enum": [
              null
            ],
            "nullable": true,
            "type": "object"
          }
        ]
      },
      "msg": {
        "type": "string"
      },
      "requestId": {
        "nullable": true,
        "type": "string"
      }
    },
    "required": [
      "code",
      "msg"
    ],
    "type": "object",
    "x-java-source": "com.lanchat.common.Result"
  },
  "ResultCut": {
    "properties": {
      "code": {
        "format": "int32",
        "type": "integer"
      },
      "data": {
        "anyOf": [
          {
            "\$ref": "#/components/schemas/Cut"
          },
          {
            "enum": [
              null
            ],
            "nullable": true,
            "type": "object"
          }
        ]
      },
      "msg": {
        "type": "string"
      },
      "requestId": {
        "nullable": true,
        "type": "string"
      }
    },
    "required": [
      "code",
      "msg"
    ],
    "type": "object",
    "x-java-source": "com.lanchat.common.Result"
  },
  "ResultError": {
    "properties": {
      "code": {
        "type": "integer"
      },
      "data": {
        "nullable": true,
        "type": "object"
      },
      "msg": {
        "type": "string"
      },
      "requestId": {
        "nullable": true,
        "type": "string"
      }
    },
    "required": [
      "code",
      "msg"
    ],
    "type": "object",
    "x-java-source": "com.lanchat.common.Result"
  },
  "ResultListChatMessage": {
    "properties": {
      "code": {
        "format": "int32",
        "type": "integer"
      },
      "data": {
        "items": {
          "\$ref": "#/components/schemas/ChatMessage"
        },
        "nullable": true,
        "type": "array"
      },
      "msg": {
        "type": "string"
      },
      "requestId": {
        "nullable": true,
        "type": "string"
      }
    },
    "required": [
      "code",
      "msg"
    ],
    "type": "object",
    "x-java-source": "com.lanchat.common.Result"
  },
  "ResultListConversationSummary": {
    "properties": {
      "code": {
        "format": "int32",
        "type": "integer"
      },
      "data": {
        "items": {
          "\$ref": "#/components/schemas/ConversationSummary"
        },
        "nullable": true,
        "type": "array"
      },
      "msg": {
        "type": "string"
      },
      "requestId": {
        "nullable": true,
        "type": "string"
      }
    },
    "required": [
      "code",
      "msg"
    ],
    "type": "object",
    "x-java-source": "com.lanchat.common.Result"
  },
  "ResultListDeviceLoginVO": {
    "properties": {
      "code": {
        "format": "int32",
        "type": "integer"
      },
      "data": {
        "items": {
          "\$ref": "#/components/schemas/DeviceLoginVO"
        },
        "nullable": true,
        "type": "array"
      },
      "msg": {
        "type": "string"
      },
      "requestId": {
        "nullable": true,
        "type": "string"
      }
    },
    "required": [
      "code",
      "msg"
    ],
    "type": "object",
    "x-java-source": "com.lanchat.common.Result"
  },
  "ResultLoginVO": {
    "properties": {
      "code": {
        "format": "int32",
        "type": "integer"
      },
      "data": {
        "anyOf": [
          {
            "\$ref": "#/components/schemas/LoginVO"
          },
          {
            "enum": [
              null
            ],
            "nullable": true,
            "type": "object"
          }
        ]
      },
      "msg": {
        "type": "string"
      },
      "requestId": {
        "nullable": true,
        "type": "string"
      }
    },
    "required": [
      "code",
      "msg"
    ],
    "type": "object",
    "x-java-source": "com.lanchat.common.Result"
  },
  "ResultMutationPage": {
    "properties": {
      "code": {
        "format": "int32",
        "type": "integer"
      },
      "data": {
        "anyOf": [
          {
            "\$ref": "#/components/schemas/MutationPage"
          },
          {
            "enum": [
              null
            ],
            "nullable": true,
            "type": "object"
          }
        ]
      },
      "msg": {
        "type": "string"
      },
      "requestId": {
        "nullable": true,
        "type": "string"
      }
    },
    "required": [
      "code",
      "msg"
    ],
    "type": "object",
    "x-java-source": "com.lanchat.common.Result"
  },
  "ResultNodePublicInfo": {
    "properties": {
      "code": {
        "format": "int32",
        "type": "integer"
      },
      "data": {
        "anyOf": [
          {
            "\$ref": "#/components/schemas/NodePublicInfo"
          },
          {
            "enum": [
              null
            ],
            "nullable": true,
            "type": "object"
          }
        ]
      },
      "msg": {
        "type": "string"
      },
      "requestId": {
        "nullable": true,
        "type": "string"
      }
    },
    "required": [
      "code",
      "msg"
    ],
    "type": "object",
    "x-java-source": "com.lanchat.common.Result"
  },
  "ResultReady": {
    "properties": {
      "code": {
        "format": "int32",
        "type": "integer"
      },
      "data": {
        "anyOf": [
          {
            "\$ref": "#/components/schemas/Ready"
          },
          {
            "enum": [
              null
            ],
            "nullable": true,
            "type": "object"
          }
        ]
      },
      "msg": {
        "type": "string"
      },
      "requestId": {
        "nullable": true,
        "type": "string"
      }
    },
    "required": [
      "code",
      "msg"
    ],
    "type": "object",
    "x-java-source": "com.lanchat.common.Result"
  },
  "ResultSessionResponse": {
    "properties": {
      "code": {
        "format": "int32",
        "type": "integer"
      },
      "data": {
        "anyOf": [
          {
            "\$ref": "#/components/schemas/SessionResponse"
          },
          {
            "enum": [
              null
            ],
            "nullable": true,
            "type": "object"
          }
        ]
      },
      "msg": {
        "type": "string"
      },
      "requestId": {
        "nullable": true,
        "type": "string"
      }
    },
    "required": [
      "code",
      "msg"
    ],
    "type": "object",
    "x-java-source": "com.lanchat.common.Result"
  },
  "ResultSnapshotPage": {
    "properties": {
      "code": {
        "format": "int32",
        "type": "integer"
      },
      "data": {
        "anyOf": [
          {
            "\$ref": "#/components/schemas/SnapshotPage"
          },
          {
            "enum": [
              null
            ],
            "nullable": true,
            "type": "object"
          }
        ]
      },
      "msg": {
        "type": "string"
      },
      "requestId": {
        "nullable": true,
        "type": "string"
      }
    },
    "required": [
      "code",
      "msg"
    ],
    "type": "object",
    "x-java-source": "com.lanchat.common.Result"
  },
  "ResultUser": {
    "properties": {
      "code": {
        "format": "int32",
        "type": "integer"
      },
      "data": {
        "anyOf": [
          {
            "\$ref": "#/components/schemas/User"
          },
          {
            "enum": [
              null
            ],
            "nullable": true,
            "type": "object"
          }
        ]
      },
      "msg": {
        "type": "string"
      },
      "requestId": {
        "nullable": true,
        "type": "string"
      }
    },
    "required": [
      "code",
      "msg"
    ],
    "type": "object",
    "x-java-source": "com.lanchat.common.Result"
  },
  "ResultVoid": {
    "properties": {
      "code": {
        "format": "int32",
        "type": "integer"
      },
      "data": {
        "nullable": true,
        "type": "object"
      },
      "msg": {
        "type": "string"
      },
      "requestId": {
        "nullable": true,
        "type": "string"
      }
    },
    "required": [
      "code",
      "msg"
    ],
    "type": "object",
    "x-java-source": "com.lanchat.common.Result"
  },
  "SessionResponse": {
    "properties": {
      "expiresAt": {
        "type": "string"
      },
      "floor": {
        "type": "string"
      },
      "latest": {
        "type": "string"
      },
      "mode": {
        "type": "string"
      },
      "recoveryId": {
        "type": "string"
      },
      "snapshotBoundary": {
        "type": "string"
      },
      "snapshotId": {
        "type": "string"
      },
      "startCursor": {
        "type": "string"
      },
      "streamEpoch": {
        "type": "string"
      }
    },
    "type": "object"
  },
  "SnapshotPage": {
    "properties": {
      "boundary": {
        "type": "string"
      },
      "items": {
        "items": {
          "\$ref": "#/components/schemas/Item"
        },
        "type": "array"
      },
      "nextPageToken": {
        "type": "string"
      },
      "snapshotComplete": {
        "type": "boolean"
      },
      "snapshotId": {
        "type": "string"
      }
    },
    "type": "object"
  },
  "TokenRefreshDTO": {
    "properties": {
      "deviceName": {
        "nullable": true,
        "type": "string"
      },
      "deviceType": {
        "description": "Not authoritative during refresh: the existing refresh token determines the device type.",
        "nullable": true,
        "type": "string"
      },
      "refreshToken": {
        "nullable": true,
        "type": "string"
      }
    },
    "type": "object",
    "x-java-source": "com.lanchat.dto.TokenRefreshDTO",
    "x-nullability-policy": "Java reference fields may be null; absence remains separate from business requiredness."
  },
  "User": {
    "properties": {
      "archiveReason": {
        "type": "string"
      },
      "archivedAt": {
        "format": "date-time",
        "type": "string"
      },
      "archivedBy": {
        "format": "int64",
        "type": "integer"
      },
      "avatar": {
        "type": "string"
      },
      "canSendBroadcast": {
        "format": "int32",
        "type": "integer"
      },
      "createTime": {
        "format": "date-time",
        "type": "string"
      },
      "deviceType": {
        "type": "string"
      },
      "id": {
        "format": "int64",
        "type": "integer"
      },
      "lastLoginAt": {
        "format": "date-time",
        "type": "string"
      },
      "muteEnd": {
        "type": "string"
      },
      "muteStart": {
        "type": "string"
      },
      "nickname": {
        "type": "string"
      },
      "online": {
        "format": "int32",
        "type": "integer"
      },
      "signature": {
        "type": "string"
      },
      "status": {
        "format": "int32",
        "type": "integer"
      },
      "updateTime": {
        "format": "date-time",
        "type": "string"
      },
      "username": {
        "type": "string"
      }
    },
    "type": "object"
  }
};
