// Generated by tooling/workspace.py generate; edit contracts/websocket/envelope.schema.json.
export const WS_PROTOCOL_VERSION = 1 as const

export interface WsEnvelope<TPayload extends Record<string, unknown> = Record<string, unknown>> {
  version: 1
  event: string
  requestId?: string | null
  clientMsgId?: string | null
  conversationId?: string | null
  timestamp: number
  payload: TPayload
}
