// Generated by tooling/workspace.py generate. Do not edit.

export interface AuthPayload extends Record<string, unknown> {
  token: string
}

export interface AuthOkPayload extends Record<string, unknown> {
  userId: number
  deviceId: number
  serverTime: number
}

export type PingPayload = Record<string, unknown>

export interface PongPayload extends Record<string, unknown> {
  serverTime: number
}

export interface SessionEndedPayload extends Record<string, unknown> {
  message: string
}

export interface ChatSendPayload extends Record<string, unknown> {
  toUserId?: number
  groupId?: number
  contentType: string
  content: string
  replyToId?: string | null
  mentionUserIds?: string | null
  isBurn: boolean
}

export interface ChatAckPayload extends Record<string, unknown> {
  clientMsgId: string
  messageId: string
  conversationId: string
  sequence: number
  mentionUserIds: string | null
  serverTime: number
  duplicated: boolean
}

export interface MessagePayload extends Record<string, unknown> {
  messageId: string | null
  clientMsgId: string | null
  conversationId: string | null
  fromNickname: string | null
  fromAvatar: string | null
  type: string | null
  contentType: string | null
  content: string | null
  replyToId: string | null
  mentionUserIds: string | null
  clientCreatedAt: string | null
  createTime: string | null
  sequence: number | null
  fromUserId: number | null
  senderDeviceId: number | null
  toUserId: number | null
  groupId: number | null
  isBurn: number | null
  burnDuration: number | null
  isRecalled: number | null
  status: number | null
}

export interface SyncRequestPayload extends Record<string, unknown> {
  positions: Record<string, number>
  limit?: number
}

export interface SyncResponsePayload extends Record<string, unknown> {
  messages: Array<MessagePayload>
  latestPositions: Record<string, number>
  deniedConversationIds: Array<string>
  hasMore: boolean
}

export interface ReadRequestPayload extends Record<string, unknown> {
  lastReadSequence: number
}

export interface ReadChangedPayload extends Record<string, unknown> {
  userId: number
  lastSequence: number
  lastReadSequence: number
  unreadCount: number
}

export interface ErrorPayload extends Record<string, unknown> {
  code: string
  message: string
  retryable: boolean
}

export type OpaquePayload = Record<string, unknown>

export interface RecoverySubscribePayload extends Record<string, unknown> {
  capability: string
  protocolVersion: number
  streamEpoch: string
}

export interface RecoverySubscribedPayload extends Record<string, unknown> {
  capability: string
  protocolVersion: number
  streamEpoch: string
}

export interface MutationAvailablePayload extends Record<string, unknown> {
  streamEpoch: string
  latestCursor: string
}

export interface ClientEventPayloads {
  AUTH: AuthPayload
  BROADCAST_ACK: OpaquePayload
  CHAT_BURN: OpaquePayload
  CHAT_DELIVER: OpaquePayload
  CHAT_READ: ReadRequestPayload
  CHAT_RECALL: OpaquePayload
  CHAT_SEND: ChatSendPayload
  FILE_TRANSFER_ANSWER: OpaquePayload
  FILE_TRANSFER_COMPLETE: OpaquePayload
  FILE_TRANSFER_FAILED: OpaquePayload
  FILE_TRANSFER_FALLBACK: OpaquePayload
  FILE_TRANSFER_OFFER: OpaquePayload
  FILE_TRANSFER_RELAY_COMPLETE: OpaquePayload
  FILE_TRANSFER_STARTED: OpaquePayload
  PING: PingPayload
  SYNC_REQUEST: SyncRequestPayload
  TYPING_START: OpaquePayload
  TYPING_STOP: OpaquePayload
  RECOVERY_SUBSCRIBE: RecoverySubscribePayload
}
export type ClientEvent = keyof ClientEventPayloads

export interface ServerEventPayloads {
  AUTH_OK: AuthOkPayload
  BROADCAST: OpaquePayload
  BROADCAST_PERMISSION_UPDATED: OpaquePayload
  BROADCAST_UPDATED: OpaquePayload
  CHAT_ACK: ChatAckPayload
  CHAT_BURN: OpaquePayload
  CHAT_DELIVER: MessagePayload
  CHAT_READ: ReadChangedPayload
  CHAT_RECALL: OpaquePayload
  CONVERSATION_CHANGED: OpaquePayload
  CONVERSATION_REMOVED: OpaquePayload
  ERROR: ErrorPayload
  FILE_TRANSFER_ANSWER: OpaquePayload
  FILE_TRANSFER_CANCELED: OpaquePayload
  FILE_TRANSFER_COMPLETE: OpaquePayload
  FILE_TRANSFER_OFFER: OpaquePayload
  FILE_TRANSFER_READY: OpaquePayload
  FILE_TRANSFER_REJECTED: OpaquePayload
  FILE_TRANSFER_RELAY_COMPLETED: OpaquePayload
  FORCE_LOGOUT: SessionEndedPayload
  FRIEND_CHANGED: OpaquePayload
  MENTION_RECEIPT_CHANGED: OpaquePayload
  ONLINE_LIST: OpaquePayload
  PONG: PongPayload
  PRESENCE_CHANGED: OpaquePayload
  PROFILE_UPDATED: OpaquePayload
  ROOM_STATUS_CHANGED: OpaquePayload
  SYNC_RESPONSE: SyncResponsePayload
  TOKEN_EXPIRED: SessionEndedPayload
  TYPING_START: OpaquePayload
  TYPING_STOP: OpaquePayload
  RECOVERY_SUBSCRIBED: RecoverySubscribedPayload
  MUTATION_AVAILABLE: MutationAvailablePayload
}
export type ServerEvent = keyof ServerEventPayloads

export const WS_EVENTS = {
  AUTH: 'AUTH',
  AUTH_OK: 'AUTH_OK',
  BROADCAST: 'BROADCAST',
  BROADCAST_ACK: 'BROADCAST_ACK',
  BROADCAST_PERMISSION_UPDATED: 'BROADCAST_PERMISSION_UPDATED',
  BROADCAST_UPDATED: 'BROADCAST_UPDATED',
  CHAT_ACK: 'CHAT_ACK',
  CHAT_BURN: 'CHAT_BURN',
  CHAT_DELIVER: 'CHAT_DELIVER',
  CHAT_READ: 'CHAT_READ',
  CHAT_RECALL: 'CHAT_RECALL',
  CHAT_SEND: 'CHAT_SEND',
  CONVERSATION_CHANGED: 'CONVERSATION_CHANGED',
  CONVERSATION_REMOVED: 'CONVERSATION_REMOVED',
  ERROR: 'ERROR',
  FILE_TRANSFER_ANSWER: 'FILE_TRANSFER_ANSWER',
  FILE_TRANSFER_CANCELED: 'FILE_TRANSFER_CANCELED',
  FILE_TRANSFER_COMPLETE: 'FILE_TRANSFER_COMPLETE',
  FILE_TRANSFER_FAILED: 'FILE_TRANSFER_FAILED',
  FILE_TRANSFER_FALLBACK: 'FILE_TRANSFER_FALLBACK',
  FILE_TRANSFER_OFFER: 'FILE_TRANSFER_OFFER',
  FILE_TRANSFER_READY: 'FILE_TRANSFER_READY',
  FILE_TRANSFER_REJECTED: 'FILE_TRANSFER_REJECTED',
  FILE_TRANSFER_RELAY_COMPLETE: 'FILE_TRANSFER_RELAY_COMPLETE',
  FILE_TRANSFER_RELAY_COMPLETED: 'FILE_TRANSFER_RELAY_COMPLETED',
  FILE_TRANSFER_STARTED: 'FILE_TRANSFER_STARTED',
  FORCE_LOGOUT: 'FORCE_LOGOUT',
  FRIEND_CHANGED: 'FRIEND_CHANGED',
  MENTION_RECEIPT_CHANGED: 'MENTION_RECEIPT_CHANGED',
  ONLINE_LIST: 'ONLINE_LIST',
  PING: 'PING',
  PONG: 'PONG',
  PRESENCE_CHANGED: 'PRESENCE_CHANGED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  ROOM_STATUS_CHANGED: 'ROOM_STATUS_CHANGED',
  SYNC_REQUEST: 'SYNC_REQUEST',
  SYNC_RESPONSE: 'SYNC_RESPONSE',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TYPING_START: 'TYPING_START',
  TYPING_STOP: 'TYPING_STOP',
  RECOVERY_SUBSCRIBE: 'RECOVERY_SUBSCRIBE',
  RECOVERY_SUBSCRIBED: 'RECOVERY_SUBSCRIBED',
  MUTATION_AVAILABLE: 'MUTATION_AVAILABLE',
} as const
