import copy
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

sys.path.insert(0, str(Path(__file__).parents[1]))
import design_tokens as design


class DesignTokenTests(unittest.TestCase):
    def setUp(self):
        self.source = design.load(design.ROOT / 'packages/design-tokens/tokens.json')

    def test_both_modes_resolve_semantics_and_keep_typed_compatibility_aliases(self):
        values = design.resolve_source(self.source)
        self.assertEqual(set(values['light']), set(values['dark']))
        for mode in design.MODES:
            self.assertEqual(values[mode]['color.message.own'], values[mode]['color.action.primary'])
            self.assertEqual(values[mode]['color.message.peer'], values[mode]['color.background.fill'])
            self.assertEqual(values[mode]['typography.body.size'], {'value': .875, 'unit': 'rem'})
        self.assertEqual(self.source['aliases']['ink'], 'color.text.primary')
        self.assertEqual(self.source['aliases']['radius-md'], 'shape.radius.medium')
        self.assertNotEqual(values['light']['color.text.primary'], values['dark']['color.text.primary'])

    def test_generation_is_deterministic_independent_of_object_insertion_order(self):
        def reverse(value):
            if isinstance(value, dict):
                return {key: reverse(value[key]) for key in reversed(value)}
            if isinstance(value, list):
                return [reverse(item) for item in value]
            return value
        expected = design.outputs(self.source)
        self.assertEqual(design.outputs(copy.deepcopy(self.source)), expected)
        self.assertEqual(design.outputs(reverse(self.source)), expected)
        for content in expected.values():
            self.assertIn('Generated by tooling/workspace.py', content.splitlines()[0])
            self.assertIn('Do not edit.', content.splitlines()[0])

    def test_primitive_change_reaches_both_outputs_without_changing_alias_routes(self):
        self.source['primitives']['palette.blue.600']['value'] = '#002244'
        generated = design.outputs(self.source)
        self.assertIn('--mx-color-action-primary: #002244;', generated['packages/design-tokens/tokens.css'])
        self.assertIn('--action-bg: var(--mx-color-action-primary);', generated['packages/design-tokens/tokens.css'])
        dart = generated['apps/flutter-prototype/lib/ui/tokens.g.dart']
        self.assertIn("'color.message.own': Color(0xff002244)", dart)
        self.assertIn("'action-bg': Color(0xff002244)", dart)
        self.assertNotIn("'material.shadow.glass':", dart)

    def test_closed_schema_and_explicit_theme_completeness(self):
        for mutate in [
            lambda d: d.update(schemaVersion=1),
            lambda d: d.update(unknown=True),
            lambda d: d['tokens']['color.text.primary'].pop('dark'),
            lambda d: d['tokens']['color.text.primary']['light'].update(extra=True),
            lambda d: d['tokens']['color.text.primary'].update(layer='presentation'),
        ]:
            data = copy.deepcopy(self.source)
            mutate(data)
            with self.assertRaises(ValueError):
                design.outputs(data)

    def test_unknown_cyclic_mismatched_and_upward_references_fail(self):
        for name, reference in [
            ('color.text.primary', 'tokens.missing'),
            ('color.text.primary', 'tokens.color.text.primary'),
            ('color.text.primary', 'primitives.size.44'),
            ('color.text.primary', 'browser.window'),
            ('motion.scale.pressed', 'tokens.component.button.press-scale'),
        ]:
            data = copy.deepcopy(self.source)
            data['tokens'][name]['light']['ref'] = reference
            with self.assertRaises(ValueError):
                design.outputs(data)
        self.source['tokens']['color.message.own']['dark']['ref'] = 'tokens.color.message.peer'
        self.source['tokens']['color.message.peer']['dark']['ref'] = 'tokens.color.message.own'
        with self.assertRaisesRegex(ValueError, 'circular'):
            design.outputs(self.source)

    def test_units_ranges_finiteness_and_font_stack_are_validated(self):
        invalid = [
            ('color', 'rgba(255, 255, 255, 1.1)'), ('color', '#nothex'),
            ('dimension', {'value': 10, 'unit': '%'}), ('dimension', {'value': -1, 'unit': 'px'}),
            ('number', True), ('number', float('nan')), ('number', float('inf')),
            ('duration', {'value': 1.5, 'unit': 'ms'}), ('cubicBezier', [2, 0, .2, 1]),
            ('cubicBezier', [0, 1]), ('fontFamily', []), ('fontFamily', ['system', 'system']),
            ('webOnly', 'red; color: black'), ('unknown', 1),
        ]
        for kind, value in invalid:
            with self.subTest(kind=kind, value=value), self.assertRaises(ValueError):
                design.css_value(kind, value)
        self.source['baseFontSize'] = False
        with self.assertRaises(ValueError):
            design.outputs(self.source)

    def test_mode_specific_dimensions_require_a_deliberate_dart_adapter(self):
        self.source['tokens']['typography.body.size']['dark']['ref'] = 'primitives.font-size.16'
        with self.assertRaisesRegex(ValueError, 'explicit Dart adapter'):
            design.outputs(self.source)

    def test_unknown_alias_and_css_name_collisions_fail(self):
        self.source['aliases']['bad-alias'] = 'missing'
        with self.assertRaisesRegex(ValueError, 'alias target'):
            design.outputs(self.source)
        del self.source['aliases']['bad-alias']
        self.source['tokens']['color.text-primary'] = copy.deepcopy(self.source['tokens']['color.text.primary'])
        with self.assertRaisesRegex(ValueError, 'collide'):
            design.outputs(self.source)

    def test_web_material_references_are_checked_for_missing_values_and_cycles(self):
        for value, error in [('var(--does-not-exist)', 'Unknown CSS'),
                             ('var(--mx-material-shadow-glass)', 'circular CSS')]:
            self.source['primitives']['web.glass-shadow.light']['value'] = value
            with self.assertRaisesRegex(ValueError, error):
                design.outputs(self.source)

    def test_duplicate_json_keys_are_rejected_before_resolution(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / 'duplicate.json'
            path.write_text('{"schemaVersion":2,"schemaVersion":2}')
            with self.assertRaisesRegex(ValueError, 'Duplicate JSON key'):
                design.load(path)

    def test_numeric_precision_and_integral_dart_duration_are_preserved(self):
        self.assertEqual(design.css_value('number', .123456789), '0.123456789')
        self.source['primitives']['duration.fast']['value'] = {'value': 1000000, 'unit': 'ms'}
        dart = design.outputs(self.source)['apps/flutter-prototype/lib/ui/tokens.g.dart']
        self.assertIn('Duration(milliseconds: 1000000)', dart)

    def test_real_cli_detects_css_and_dart_drift_and_never_repairs_during_check(self):
        with tempfile.TemporaryDirectory(prefix='MeshX design validation ') as directory:
            root = Path(directory)
            catalog = design.load(design.ROOT / 'packages/design-tokens/components.json')
            inputs = ['packages/design-tokens/tokens.json', 'packages/design-tokens/components.json',
                      'contracts/websocket/events.schema.json', 'apps/web/src/components/base/UiIcon.vue']
            inputs += [value['spec'] for value in catalog['components'].values() if 'spec' in value]
            for name in inputs:
                (root/name).parent.mkdir(parents=True, exist_ok=True)
                (root/name).write_bytes((design.ROOT/name).read_bytes())
            outputs = design.outputs(self.source)
            for name, content in outputs.items():
                (root/name).parent.mkdir(parents=True, exist_ok=True)
                (root/name).write_text(content)
            argv = [sys.executable, str(design.ROOT/'tooling/design_tokens.py'), '--root', str(root), '--check']
            valid = subprocess.run(argv, capture_output=True, text=True)
            self.assertEqual(valid.returncode, 0, valid.stderr)
            catalog_path = root/'packages/design-tokens/components.json'
            for mutate, message in [
                (lambda c: c['components'].pop('avatar'), 'six foundation'),
                (lambda c: c['components']['message']['stateCoverage'].pop('selected'), 'state coverage'),
                (lambda c: c['components']['button'].update(spec='missing.md'), 'Missing component specification'),
                (lambda c: c['iconSemantics']['send'].update(asset='invented-icon'), 'Unknown icon asset'),
            ]:
                invalid = copy.deepcopy(catalog)
                mutate(invalid)
                catalog_path.write_text(json.dumps(invalid))
                result = subprocess.run(argv, capture_output=True, text=True)
                self.assertEqual(result.returncode, 1)
                self.assertIn(message, result.stderr)
            catalog_path.write_text(json.dumps(catalog))
            for name, content in outputs.items():
                drifted = content + '\n// deliberate drift\n'
                (root/name).write_text(drifted)
                result = subprocess.run(argv, capture_output=True, text=True)
                self.assertEqual(result.returncode, 1)
                self.assertIn(name, result.stderr)
                self.assertEqual((root/name).read_text(), drifted)
                (root/name).write_text(content)
            data = copy.deepcopy(self.source)
            del data['tokens']['color.text.primary']['dark']
            (root/'packages/design-tokens/tokens.json').write_text(json.dumps(data))
            result = subprocess.run(argv, capture_output=True, text=True)
            self.assertEqual(result.returncode, 1)
            self.assertIn('color.text.primary', result.stderr)


if __name__ == '__main__':
    unittest.main()
