"""Small, deliberately bounded WS schema-to-TypeScript/Dart generator."""
import json
import copy
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def java_envelope(envelope):
    """Generate the existing Lombok DTO without changing field order/defaults."""
    lines = ['package com.lanchat.dto;', '', 'import lombok.Data;', '',
             'import java.util.LinkedHashMap;', 'import java.util.Map;', '',
             '/** Generated from contracts/websocket/envelope.schema.json. Do not edit. */',
             '@Data', 'public class WebSocketEnvelope {', '']
    kinds = {'integer': 'Long', 'string': 'String', 'object': 'Map<String, Object>'}
    for name, field in envelope['properties'].items():
        kind = field['type']
        if isinstance(kind, list):
            if kind != ['string', 'null']:
                raise ValueError('Unsupported Java envelope union: ' + name)
            kind = 'string'
        typ = 'Integer' if name == 'version' else kinds[kind]
        default = (' = ' + str(field['const'])) if 'const' in field else ''
        if name == 'payload':
            default = ' = new LinkedHashMap<>()'
        lines.append(f'    private {typ} {name}{default};')
    return '\n'.join([*lines, '}', ''])


def ts_type(schema):
    if '$ref' in schema:
        return schema['$ref'].split('/')[-1]
    kind = schema.get('type')
    if isinstance(kind, list):
        return ' | '.join(ts_type({**schema, 'type': k}) for k in kind)
    if kind == 'array':
        return f'Array<{ts_type(schema["items"])}>'
    if kind == 'object':
        return 'Record<string, ' + (ts_type(schema['additionalProperties']) if isinstance(schema.get('additionalProperties'), dict) else 'unknown') + '>'
    return {'string': 'string', 'integer': 'number', 'boolean': 'boolean', 'null': 'null'}[kind]


def dart_type(schema):
    if '$ref' in schema:
        return schema['$ref'].split('/')[-1]
    kind = schema['type']
    if isinstance(kind, list):
        if len(kind) != 2 or 'null' not in kind:
            raise ValueError('Only nullable unions are supported')
        return dart_type({**schema, 'type': next(k for k in kind if k != 'null')}) + '?'
    if kind == 'array':
        return f'List<{dart_type(schema["items"])}>'
    if kind == 'object':
        value = schema.get('additionalProperties')
        return 'Map<String, ' + (dart_type(value) if isinstance(value, dict) else 'dynamic') + '>'
    return {'string': 'String', 'integer': 'int', 'boolean': 'bool'}[kind]


def decode(schema, expr):
    if '$ref' in schema:
        return dart_type(schema) + '.fromJson(Map<String, dynamic>.from(' + expr + ' as Map))'
    kind = schema['type']
    if isinstance(kind, list):
        inner = {**schema, 'type': next(k for k in kind if k != 'null')}
        return expr + ' == null ? null : ' + decode(inner, expr)
    if kind == 'array':
        return '(' + expr + ' as List).map((value) => ' + decode(schema['items'], 'value') + ').toList()'
    if kind == 'object':
        return dart_type(schema) + '.from(' + expr + ' as Map)'
    return expr + ' as ' + dart_type(schema)


def encode(schema, expr):
    if '$ref' in schema:
        return expr + '.toJson()'
    if schema.get('type') == 'array' and '$ref' in schema['items']:
        return expr + '.map((value) => value.toJson()).toList()'
    return expr


def outputs():
    schema = json.loads((ROOT / 'contracts/websocket/events.schema.json').read_text())
    envelope = json.loads((ROOT / 'contracts/websocket/envelope.schema.json').read_text())
    ts = ['// Generated by tooling/workspace.py generate. Do not edit.', '']
    dart = ['// Generated by tooling/workspace.py generate. Do not edit.', '// ignore_for_file: constant_identifier_names',
            "import 'wire_validation.dart';", '',
            f"const wsProtocolVersion = {envelope['properties']['version']['const']};", '']
    for name, model in schema['$defs'].items():
        props = model.get('properties', {})
        if not props:
            ts += [f'export type {name} = Record<string, unknown>', '']
            continue
        ts += [f'export interface {name} extends Record<string, unknown> {{']
        dart += [f'class {name} {{']
        for key, field in props.items():
            optional = key not in model['required']
            ts += [f"  {key}{'?' if optional else ''}: {ts_type(field)}"]
            typ = dart_type(field)
            if optional and not typ.endswith('?'):
                typ += '?'
            dart += [f'  final {typ} {key};']
        dart += [f'  const {name}({{']
        for key in props:
            dart += [f"    {'required ' if key in model['required'] else ''}this.{key},"]
        dart += ['  });', f'  factory {name}.fromJson(Map<String, dynamic> json) => {name}(']
        for key, field in props.items():
            expr = f"json['{key}']"
            decoded = decode(field, expr)
            if key not in model['required'] and not isinstance(field.get('type'), list):
                decoded = expr + ' == null ? null : ' + decoded
            dart += [f'    {key}: {decoded},']
        dart += ['  );', '  Map<String, dynamic> toJson() => {']
        for key, field in props.items():
            guard = f'if ({key} != null) ' if key not in model['required'] else ''
            dart += [f"    {guard}'{key}': {encode(field, key)},"]
        dart += ['  };', '}', '']
        ts += ['}', '']
    for direction in ['client', 'server']:
        name = direction.title() + 'EventPayloads'
        ts += [f'export interface {name} {{']
        for event, info in schema['x-events'].items():
            if direction in info:
                ts += [f"  {event}: {info[direction]['payload']}"]
        ts += ['}', f'export type {direction.title()}Event = keyof {name}', '']
    dart += ['abstract final class WsEvents {']
    ts += ['export const WS_EVENTS = {']
    for event in schema['x-events']:
        dart += [f"  static const {event.lower()} = '{event}';"]
        ts += [f"  {event}: '{event}',"]
    dart += ['}', '']
    ts += ['} as const', '']
    wire = copy.deepcopy(envelope)
    wire.pop('$schema', None)
    dart += [
        'class WsFrame {', '  WsFrame._(this._json);', '  final Map<String, dynamic> _json;',
        '  factory WsFrame.fromJson(Map<String, dynamic> json) {',
        '    validateWire(json, _wsEnvelopeSchema, _wsDefinitions);',
        '    return WsFrame._(Map<String, dynamic>.unmodifiable(json));', '  }',
        "  String get event => _json['event'] as String;",
        "  Map<String, dynamic> get payload => Map<String, dynamic>.from(_json['payload'] as Map);",
        "  String? get requestId => _json['requestId'] as String?;",
        '  // Unknown server events remain parseable; callers explicitly ignore or reject them.',
        '  bool isKnown(String direction) => (_wsFrames[direction] ?? const [])',
        "      .any((branch) => branch['properties']['event']['const'] == event);",
        '  void validateKnownEvent(String direction) {',
        "    if (!_wsFrames.containsKey(direction)) throw ArgumentError.value(direction, 'direction');",
        "    validateWire(_json, {'anyOf': _wsFrames[direction]}, _wsDefinitions);", '  }',
        '  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);', '}', '',
        'const Map<String, dynamic> _wsEnvelopeSchema = ' + json.dumps(wire, ensure_ascii=False).replace('$', r'\$') + ';',
        'const Map<String, dynamic> _wsDefinitions = ' + json.dumps(schema['$defs'], ensure_ascii=False).replace('$', r'\$') + ';',
        'const Map<String, List<dynamic>> _wsFrames = ' + json.dumps({direction: [branch for branch in schema['anyOf']
            if branch['x-direction'] == direction] for direction in ('client', 'server')}, ensure_ascii=False).replace('$', r'\$') + ';', '']
    return {'packages/protocol/src/events.ts': '\n'.join(ts),
            'apps/flutter-prototype/lib/data/ws_contract.g.dart': '\n'.join(dart),
            'services/server/src/main/java/com/lanchat/dto/WebSocketEnvelope.java': java_envelope(envelope)}


def check(schema=None, source=None, additional_sources=None):
    """Fail on handler event/key drift. Behavioral authorization remains in Java tests."""
    import re
    schema = schema or json.loads((ROOT / 'contracts/websocket/events.schema.json').read_text())
    source = source or (ROOT / 'services/server/src/main/java/com/lanchat/websocket/ChatWebSocketHandler.java').read_text()
    errors = []
    switch = source.split('switch (event) {', 1)[1].split('default ->', 1)[0]
    incoming = {name for case in re.findall(r'case\s+(.+?)\s*->', switch, re.S)
                for name in re.findall(r'"([A-Z_]+)"', case)}
    declared = {name for name, info in schema['x-events'].items() if 'client' in info}
    if incoming != declared:
        errors.append(f'WS client event drift: handler-only={sorted(incoming-declared)}, schema-only={sorted(declared-incoming)}')
    event_arguments = re.findall(r'envelope\(\s*([^,]+),', source)
    outgoing = {name for argument in event_arguments for name in re.findall(r'"([A-Z_]+)"', argument)}
    if additional_sources is None:
        path = 'services/server/src/main/java/com/lanchat/recovery/MutationHintDispatcher.java'
        additional_sources = {path: (ROOT / path).read_text()}
    for path, emitter in additional_sources.items():
        for argument in re.findall(r'\.setEvent\(([^)]+)\)', emitter):
            match = re.fullmatch(r'\s*"([A-Z_]+)"\s*', argument)
            if match:
                outgoing.add(match.group(1))
            else:
                errors.append(f'WS dynamic external event dispatch changed: {path}')
    typing_cases = re.findall(r'case\s+([^;]+?)\s*->\s*handleTyping\(session, incoming, event\)', switch)
    outgoing.update(name for case in typing_cases for name in re.findall(r'"([A-Z_]+)"', case))
    session_choices = re.findall(r'String event = jwtUtil\.isAccessToken\(token\) \? ([^;]+);', source)
    outgoing.update(name for choice in session_choices for name in re.findall(r'"([A-Z_]+)"', choice))
    unknown_arguments = [arg for arg in event_arguments if not re.search(r'"[A-Z_]+"', arg) and arg.strip() not in {'String event', 'event'}]
    if unknown_arguments or event_arguments.count('event') != 2 or len(session_choices) != 1 or not typing_cases:
        errors.append('WS dynamic event dispatch changed; extend source inventory explicitly')
    declared_outgoing = {name for name, info in schema['x-events'].items() if 'server' in info}
    if outgoing != declared_outgoing:
        errors.append(f'WS server event drift: handler-only={sorted(outgoing-declared_outgoing)}, schema-only={sorted(declared_outgoing-outgoing)}')
    expected_branches = {(event, direction, '#/$defs/' + info['payload'])
                         for event, directions in schema['x-events'].items() for direction, info in directions.items()}
    actual_branches = [(branch['properties']['event']['const'], branch['x-direction'], branch['properties']['payload']['$ref'])
                       for branch in schema['anyOf']]
    if set(actual_branches) != expected_branches or len(actual_branches) != len(expected_branches):
        errors.append('WS schema branches differ from event direction/payload registry')
    envelope = json.loads((ROOT / 'contracts/websocket/envelope.schema.json').read_text())
    for branch in schema['anyOf']:
        fields = branch['properties']
        label = branch.get('title', fields['event']['const'])
        if not set(envelope['required']).issubset(branch.get('required', [])):
            errors.append(f'WS event dropped common required envelope fields: {label}')
        if fields['version'].get('const') != envelope['properties']['version']['const']:
            errors.append(f'WS event version differs from common envelope: {label}')
        for name in ('requestId', 'clientMsgId', 'conversationId'):
            # An event may require a non-null identifier; all other metadata
            # must retain the common wire shape rather than a second definition.
            expected_type = envelope['properties'][name]['type']
            if name in branch.get('required', []):
                expected_type = 'string'
            if fields.get(name, {}).get('type') != expected_type:
                errors.append(f'WS event metadata differs from common envelope: {label}/{name}')
    for method, model, variable in [('sendChatAck', 'ChatAckPayload', 'ackPayload'),
                                    ('messagePayload', 'MessagePayload', 'payload'),
                                    ('handleSyncRequest', 'SyncResponsePayload', 'payload'),
                                    ('notifyConversationRead', 'ReadChangedPayload', 'payload')]:
        match = re.search(r'(?:private|public)\s+[\w<>, ?]+\s+' + method + r'\s*\([^)]*\)\s*\{', source)
        if not match:
            errors.append(f'Cannot locate WS payload method: {method}')
            continue
        start = match.end()
        depth = 1
        end = start
        while depth and end < len(source):
            depth += (source[end] == '{') - (source[end] == '}')
            end += 1
        keys = set(re.findall(r'\b' + variable + r'\.put\("(\w+)"', source[start:end]))
        expected = set(schema['$defs'][model]['properties'])
        if keys != expected:
            errors.append(f'WS payload fields differ: {method} -> {model}: {sorted(keys ^ expected)}')
    return errors
