"""Generate a small transport-free Dart REST slice and all TS operation identities.

Java/MVC owns fields and routes. This generator refuses shapes it cannot represent;
it does not install tools, implement auth/storage, or invent a second API schema.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def nullable_shape(schema):
    if 'anyOf' in schema:
        branches = schema['anyOf']
        nonnull = [part for part in branches if part.get('enum') != [None]]
        if len(nonnull) != 1 or len(branches) != 2:
            raise ValueError('Dart model supports only explicit nullable anyOf, not arbitrary unions')
        return nonnull[0], True
    return schema, bool(schema.get('nullable'))


def dart_type(schema):
    shape, nullable = nullable_shape(schema)
    if '$ref' in shape:
        result = 'Rest' + shape['$ref'].split('/')[-1]
    else:
        kind = shape.get('type')
        if kind == 'array':
            result = 'List<' + dart_type(shape['items']) + '>'
        elif kind == 'object':
            result = 'Map<String, dynamic>'
        else:
            result = {'string': 'String', 'integer': 'int', 'number': 'num', 'boolean': 'bool'}[kind]
    return result + ('?' if nullable else '')


def decode(schema, expr):
    shape, nullable = nullable_shape(schema)
    if '$ref' in shape:
        result = 'Rest' + shape['$ref'].split('/')[-1] + '.fromJson(Map<String, dynamic>.from(' + expr + ' as Map))'
    elif shape.get('type') == 'array':
        result = '(' + expr + ' as List).map((item) => ' + decode(shape['items'], 'item') + ').toList()'
    elif shape.get('type') == 'object':
        result = 'Map<String, dynamic>.from(' + expr + ' as Map)'
    else:
        result = expr + ' as ' + dart_type({**shape, 'nullable': False})
    return expr + ' == null ? null : ' + result if nullable else result


def encode(schema, expr):
    shape, nullable = nullable_shape(schema)
    if '$ref' in shape:
        return expr + ('?' if nullable else '') + '.toJson()'
    if shape.get('type') == 'array':
        return expr + ('?' if nullable else '') + '.map((item) => ' + encode(shape['items'], 'item') + ').toList()'
    return expr


def referenced_models(value):
    if isinstance(value, dict):
        if '$ref' in value:
            yield value['$ref'].split('/')[-1]
        for child in value.values():
            yield from referenced_models(child)
    elif isinstance(value, list):
        for child in value:
            yield from referenced_models(child)


def outputs():
    api = json.loads((ROOT / 'contracts/rest/openapi.json').read_text())
    config = json.loads((ROOT / 'tooling/contracts/generation.json').read_text())
    if api['openapi'] != config['openapiVersion'] or config['version'] != 1:
        raise ValueError('Review the generator before changing OpenAPI/config version')
    operations = {}
    for path, methods in api['paths'].items():
        for method, operation in methods.items():
            if method not in {'get', 'put', 'post', 'delete', 'patch', 'head', 'options', 'trace'}:
                continue
            name = operation['operationId']
            if name in operations:
                raise ValueError('Duplicate operationId: ' + name)
            base = '/'.join(path.split('/')[:3])
            if not base.startswith('/api/v'):
                raise ValueError('Review non-versioned API base: ' + path)
            operations[name] = {'method': method.upper(), 'path': path,
                                'relativePath': path[len(base):], 'operation': operation}
    selected = config['dartOperations']
    if not selected or len(set(selected)) != len(selected) or set(selected) - set(operations):
        raise ValueError('Dart operation selection is empty, duplicated or missing from MVC export')
    schemas = api['components']['schemas']
    needed = set()
    pending = list(referenced_models([operations[name]['operation'] for name in selected]))
    while pending:
        name = pending.pop()
        if name in needed:
            continue
        if name not in schemas:
            raise ValueError('Missing schema: ' + name)
        needed.add(name)
        pending.extend(referenced_models(schemas[name]))

    ts = ["// Generated by tooling/workspace.py generate. Do not edit.",
          "import type { components } from './rest.js'", '',
          "export type ApiResult<T> = Omit<components['schemas']['ResultVoid'], 'data'> & { data?: T | null }", '',
          'export const REST_OPERATIONS = {']
    for name, info in sorted(operations.items()):
        ts.append('  ' + json.dumps(name) + ': ' + json.dumps({k: info[k] for k in ('method', 'path', 'relativePath')}) + ',')
    ts += ['} as const', '']
    normalized_types = schemas['LoginDTO']['properties']['deviceType']['x-normalized-values']
    ts += ['export const DEVICE_TYPES = ' + json.dumps(normalized_types) + ' as const',
           'export type DeviceType = typeof DEVICE_TYPES[number]', '']
    dart = ['// Generated by tooling/workspace.py generate. Do not edit.',
            '// ignore_for_file: constant_identifier_names',
            "import 'wire_validation.dart';", '',
            'class RestOperation {',
            '  const RestOperation(this.method, this.path, this.relativePath);',
            '  final String method, path, relativePath;',
            "  String atBase(String base) => '${base.replaceFirst(RegExp(r'/$'), '')}$relativePath';",
            '}', '', 'abstract final class RestOperations {']
    for name in selected:
        info = operations[name]
        dart.append(f"  static const {name} = RestOperation('{info['method']}', '{info['path']}', '{info['relativePath']}');")
    dart += ['}', '', 'const restDeviceTypes = ' + json.dumps(normalized_types) + ';', '']
    for name in sorted(needed):
        model = schemas[name]
        if model.get('type') != 'object' or not model.get('properties'):
            raise ValueError('Dart slice needs a reviewed object model: ' + name)
        fields = model['properties']
        required = set(model.get('required', []))
        cls = 'Rest' + name
        dart += [f'class {cls} {{', f'  {cls}._(this._json);',
                 '  final Map<String, dynamic> _json;',
                 f'  factory {cls}({{']
        for key, field in fields.items():
            typ = dart_type(field)
            if key not in required and not typ.endswith('?'):
                typ += '?'
            dart.append(f"    {'required ' if key in required else ''}{typ} {key},")
        dart += [f'  }}) => {cls}.fromJson({{']
        for key, field in fields.items():
            shape, nullable = nullable_shape(field)
            expr = encode({**shape, 'nullable': nullable or key not in required}, key)
            marker = '?' if key not in required else ''
            dart.append(f"    '{key}': {marker}{expr},")
        dart += ['  });', f'  factory {cls}.fromJson(Map<String, dynamic> json) {{',
                 f"    validateWire(json, restModelSchemas['{name}'] as Map<String, dynamic>, restModelSchemas);",
                 f'    return {cls}._(Map<String, dynamic>.unmodifiable(json));', '  }']
        for key, field in fields.items():
            typ = dart_type(field)
            expression = decode(field, f"_json['{key}']")
            if key not in required:
                if not typ.endswith('?'):
                    typ += '?'
                expression = f"_json['{key}'] == null ? null : " + decode({**nullable_shape(field)[0], 'nullable': False}, f"_json['{key}']")
            dart.append(f'  {typ} get {key} => {expression};')
        dart += ['  // Preserve absent vs explicit null and unknown forward-compatible fields.',
                 '  Map<String, dynamic> toJson() => Map<String, dynamic>.from(_json);', '}', '']
    # JSON is valid Dart map literal syntax. Do not embed server credentials or examples.
    dart += ['const Map<String, dynamic> restModelSchemas = ' +
             json.dumps({name: schemas[name] for name in sorted(needed)}, ensure_ascii=False, indent=2).replace('$', r'\$') + ';', '']
    return {'packages/protocol/src/rest-contract.ts': '\n'.join(ts),
            'apps/flutter-prototype/lib/data/rest_contract.g.dart': '\n'.join(dart)}
