#!/usr/bin/env python3
"""Repository-local context, generated references and verification. Python stdlib only."""
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import design_tokens
import protocol_types
import verification
import rest_contracts
import contract_compatibility

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "tooling/workspace.json"
SKIP = {"node_modules", "target", "build", "dist", "dist-mobile", "dist-desktop",
        ".git", ".gradle", ".swiftpm", ".dart_tool", "ephemeral", "Pods", "DerivedData", "__pycache__", "gen", "public"}
CONTEXT_SUMMARY_MAX_BYTES = 4096
ROOT_AGENTS_MAX_BYTES = 4096


def source_files(folder: Path, extensions: set[str]) -> list[Path]:
    found = []
    for directory, folders, files in os.walk(folder):
        folders[:] = sorted(name for name in folders if name not in SKIP)
        found.extend(Path(directory) / name for name in sorted(files)
                     if Path(name).suffix in extensions)
    return sorted(found)


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def manifest() -> dict:
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def generated_envelope(schema: dict) -> str:
    if schema.get("type") != "object" or schema.get("additionalProperties") is not True:
        raise ValueError("Unsupported envelope schema: expected an extensible object")
    fields = []
    for name, field in schema["properties"].items():
        if name == "payload" and field == {"type": "object", "additionalProperties": True}:
            value = "TPayload"
        elif set(field) <= {"type", "const"} and isinstance(field["type"], str) and field["type"] in {"integer", "string"}:
            value = json.dumps(field["const"]) if "const" in field else {"integer": "number", "string": "string"}[field["type"]]
        elif field == {"type": ["string", "null"]}:
            value = "string | null"
        else:
            raise ValueError(f"Unsupported envelope field: {name}; extend generator and verification together")
        optional = "" if name in schema["required"] else "?"
        fields.append(f"  {name}{optional}: {value}")
    return ("// Generated by tooling/workspace.py generate; edit contracts/websocket/envelope.schema.json.\n"
            + f"export const WS_PROTOCOL_VERSION = {schema['properties']['version']['const']} as const\n"
            + "\n"
            + "export interface WsEnvelope<TPayload extends Record<string, unknown> = Record<string, unknown>> {\n"
            + "\n".join(fields) + "\n}\n")


def generated_outputs() -> dict[str, str]:
    schema = json.loads(read("contracts/websocket/envelope.schema.json"))
    return {
        "packages/protocol/src/envelope.ts": generated_envelope(schema),
        **design_tokens.outputs(),
        **protocol_types.outputs(),
        **rest_contracts.outputs(),
    }


def generate(check: bool) -> list[str]:
    errors = []
    for name, expected in generated_outputs().items():
        path = ROOT / name
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                errors.append(f"Generated file is stale: {name}; run python3 tooling/workspace.py generate")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    return errors


def check_contracts() -> list[str]:
    errors = []
    schema = json.loads(read("contracts/websocket/envelope.schema.json"))
    expected = {name: {"integer": "Integer" if name == "version" else "Long", "string": "String", "object": "Map<String,Object>"}[field["type"] if isinstance(field["type"], str) else field["type"][0]]
                for name, field in schema["properties"].items()}
    java = read("services/server/src/main/java/com/lanchat/dto/WebSocketEnvelope.java")
    actual = {name: re.sub(r"\s+", "", kind) for kind, name in
              re.findall(r"private\s+([\w<>?, ]+?)\s+(\w+)\s*(?:=|;)", java)}
    if actual != expected or not re.search(r"private Integer version = 1;", java):
        errors.append("WebSocketEnvelope.java shape differs from envelope.schema.json; update both sides and compatibility tests")
    if read("packages/protocol/src/envelope.ts") != generated_envelope(schema):
        errors.append("Generated TypeScript envelope is stale")
    for name, expected in {**design_tokens.outputs(), **protocol_types.outputs(), **rest_contracts.outputs()}.items():
        if not (ROOT / name).exists() or read(name) != expected:
            errors.append(f"Generated contract/design file is stale: {name}")
    return errors + protocol_types.check() + design_tokens.check() + contract_compatibility.check_files()


def check_context_entries(config: dict) -> list[str]:
    errors = []
    for module in config["modules"]:
        base = ROOT / module["path"]
        for entry in module["entries"]:
            if Path(entry).suffix == ".md":
                continue
            if not (base / entry).is_file():
                errors.append(f"Missing module entry: {module['path']}/{entry}")
        for scope in module["verificationScopes"]:
            if scope != "workspace" and scope not in config["verification"]:
                errors.append(f"Unknown verification scope: {module['id']} -> {scope}")
        context = module_context(module)
        summaries = (format_context(context), json.dumps(context, ensure_ascii=False, indent=2))
        if max(len(text.encode("utf-8")) for text in summaries) > CONTEXT_SUMMARY_MAX_BYTES:
            errors.append(f"Module context summary exceeds {CONTEXT_SUMMARY_MAX_BYTES} bytes: {module['id']}")
    modules = {item["id"]: item for item in config["modules"]}
    for route in config.get("taskRoutes", []):
        for module_id in route["modules"]:
            if module_id not in modules:
                errors.append(f"Unknown task module: {route['id']} -> {module_id}")
        for path in [*route["entries"], *route["tests"]]:
            if not (ROOT / path).is_file():
                errors.append(f"Missing task entry: {route['id']} -> {path}")
        for scope in route["verificationScopes"]:
            if scope not in config["verification"]:
                errors.append(f"Unknown task verification: {route['id']} -> {scope}")
        if all(module_id in modules for module_id in route["modules"]):
            context = task_context(route, modules)
            if max(len(value.encode("utf-8")) for value in
                   (format_context(context), json.dumps(context, ensure_ascii=False, indent=2))) > CONTEXT_SUMMARY_MAX_BYTES:
                errors.append(f"Task context summary exceeds {CONTEXT_SUMMARY_MAX_BYTES} bytes: {route['id']}")
    for scope, commands in config["verification"].items():
        if not commands:
            errors.append(f"Empty verification scope: {scope}")
        for command in commands:
            if not command.get("argv") or not command.get("cwd"):
                errors.append(f"Invalid command in scope: {scope}")
    for group, scopes in config.get("verificationGroups", {}).items():
        if not scopes or len(set(scopes)) != len(scopes):
            errors.append(f"Empty or duplicate verification group: {group}")
        for scope in scopes:
            if scope not in config["verification"]:
                errors.append(f"Unknown verification group member: {group} -> {scope}")
    return errors


def check_workspace() -> list[str]:
    config = manifest()
    errors = check_context_entries(config)
    errors += check_shared_dependencies()
    return errors + generate(True) + check_contracts()


def check_shared_dependencies() -> list[str]:
    """Shared source must stay usable without a UI or native SDK installed."""
    errors = []
    allowed = {"protocol": set(), "domain-ts": {"protocol"}, "platform-ports": {"protocol", "domain-ts"}}
    imports = re.compile(r"(?:\bfrom\s*|\bimport\s*\(?\s*|\brequire\s*\(\s*)['\"]([^'\"]+)['\"]")
    for package, dependencies in allowed.items():
        for path in source_files(ROOT / "packages" / package, {".ts"}):
            text = path.read_text(encoding="utf-8")
            for specifier in imports.findall(text):
                if not specifier.startswith("."):
                    errors.append(f"Shared core must not import runtime {specifier}: {path.relative_to(ROOT)}")
                    continue
                target = (path.parent / specifier).resolve()
                if not any(target.is_relative_to((ROOT / "packages" / dep).resolve()) for dep in {package, *dependencies}):
                    errors.append(f"Dependency direction violated: {path.relative_to(ROOT)} -> {specifier}")
            if re.search(r"\b(?:window|document|navigator|localStorage|indexedDB)\s*[.\[]", text):
                errors.append(f"Browser state belongs in adapters: {path.relative_to(ROOT)}")

    return errors


def instruction_chain(module_path: str) -> list[str]:
    """Repository files only; do not read user/global configuration or unrelated modules."""
    current = ROOT
    chain = []
    for part in [None, *Path(module_path).parts]:
        if part is not None:
            current = current / part
        for filename in ("AGENTS.override.md", "AGENTS.md"):
            path = current / filename
            if path.is_file() and path.stat().st_size:
                chain.append(path.relative_to(ROOT).as_posix())
                break
    return chain


def module_context(item: dict) -> dict:
    instructions = instruction_chain(item["path"])
    entries = [f"{item['path']}/{entry}" for entry in item["entries"]
               if Path(entry).suffix != ".md" and (ROOT / item["path"] / entry).is_file()]
    return {
        "module": item["id"], "path": item["path"], "role": item["role"],
        "instructions": instructions,
        "instructionBytes": sum((ROOT / path).stat().st_size for path in instructions),
        "entries": entries,
        "relatedDocs": item["relatedDocs"],
        "verificationScopes": item["verificationScopes"],
    }


def task_context(item: dict, modules: dict) -> dict:
    instructions = list(dict.fromkeys(path for module_id in item["modules"]
                                     for path in instruction_chain(modules[module_id]["path"])))
    return {"task": item["id"], "path": item["id"], "role": item["role"],
            "instructions": instructions,
            "instructionBytes": sum((ROOT / path).stat().st_size for path in instructions),
            "entries": item["entries"], "tests": item["tests"],
            "relatedDocs": item["relatedDocs"], "verificationScopes": item["verificationScopes"]}


def format_context(item: dict) -> str:
    related_docs = [doc for doc in item["relatedDocs"] if (ROOT / doc["path"]).is_file()]
    lines = [f"{item['path']}: {item['role']}",
             "Read: " + " -> ".join(item["instructions"]),
             f"Repository instructions: {item['instructionBytes']} UTF-8 bytes (not token usage; content is not loaded)",
             "Entries:", *[f"  {path}" for path in item["entries"]],
             *(["Tests:", *[f"  {path}" for path in item["tests"]]] if item.get("tests") else []),
             *(["Read only when relevant:", *[f"  {doc['when']}: {doc['path']}" for doc in related_docs]] if related_docs else []),
             "Verification (select affected scopes; no commands executed):",
             *[f"  python3 tooling/workspace.py verify {scope}" for scope in item["verificationScopes"]],
             "  Add platform and device checks when runtime behavior changes."]
    return "\n".join(lines) + "\n"


def run_command(command: dict, extra: list[str], dry_run: bool) -> int:
    result = verification.run_step({"scope": "command", "name": "command", **command}, ROOT, extra, dry_run)
    verification.print_step(result)
    return verification.exit_code(result)


def verification_plan(scope: str) -> list[dict]:
    config = manifest()
    commands = config["verification"]
    scopes = config.get("verificationGroups", {}).get(scope, [scope])
    if not scopes:
        raise ValueError(f"Empty verification group: {scope}")
    plan = []
    for selected in scopes:
        if selected not in commands or not commands[selected]:
            raise ValueError(f"Unknown or empty verification scope: {selected}")
        for index, command in enumerate(commands[selected], 1):
            plan.append({**command, "scope": selected, "name": command.get("name", str(index))})
    return plan


class WorkspaceParser(argparse.ArgumentParser):
    def error(self, message: str) -> None:
        print(f"[FAIL] invalid invocation: {message}", file=sys.stderr)
        super().error(message)


def report(errors: list[str]) -> int:
    for error in errors:
        print(f"ERROR: {error}", file=sys.stderr)
    if not errors:
        print("Workspace checks passed.")
    return bool(errors)


def main() -> int:
    parser = WorkspaceParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    gen = sub.add_parser("generate", help="Generate compact source maps and protocol types")
    gen.add_argument("--check", action="store_true")
    sub.add_parser("check", help="Check context links, modules, shared boundaries and generated files")
    sub.add_parser("check-contracts", help="Check existing contract/design sources and generated files")
    context = sub.add_parser("context", help="Print a small module entry, without reading unrelated platforms")
    context.add_argument("scope", choices=[m["id"] for m in manifest()["modules"]] +
                         [item["id"] for item in manifest().get("taskRoutes", [])])
    context.add_argument("--json", action="store_true", help="Emit the same bounded navigation as structured data")
    scopes = [*manifest()["verification"], *manifest().get("verificationGroups", {})]
    verify = sub.add_parser("verify", help="Run the affected scope's real checks; no dependency installation")
    verify.add_argument("scope", choices=scopes)
    verify.add_argument("--dry-run", action="store_true")
    verify.add_argument("--report", help="Write JSON results to this path (relative to invocation cwd)")
    doctor = sub.add_parser("doctor", help="Check command/input availability; tests and builds remain NOT_RUN")
    doctor.add_argument("scope", nargs="?", default="all", choices=scopes)
    doctor.add_argument("--report", help="Write JSON prerequisite results")
    # Arguments after -- are forwarded to each command of a single native/server scope.
    raw = sys.argv[1:]
    split = raw.index("--") if "--" in raw else len(raw)
    args = parser.parse_args(raw[:split])
    extra = raw[split + 1:]
    if extra and (args.command != "verify" or args.scope not in {"server", "android"}):
        parser.error("Only server/android accept command arguments after --")
    if args.command == "generate":
        return report(generate(args.check))
    if args.command == "check":
        return report(check_workspace())
    if args.command == "check-contracts":
        return report(check_contracts())
    if args.command == "context":
        config = manifest()
        modules = {item["id"]: item for item in config["modules"]}
        if args.scope in modules:
            context = module_context(modules[args.scope])
        else:
            item = next(item for item in config["taskRoutes"] if item["id"] == args.scope)
            context = task_context(item, modules)
        print(json.dumps(context, ensure_ascii=False, indent=2) if args.json else format_context(context), end="\n" if args.json else "")
        return 0
    plan = verification_plan(args.scope)
    result = (verification.doctor(plan, ROOT) if args.command == "doctor" else
              verification.run_plan(plan, ROOT, extra, args.dry_run))
    result["requestedScope"] = args.scope
    verification.write_report(result, args.report)
    return result["exitCode"]


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, KeyError) as error:
        print(f"[FAIL] {error}", file=sys.stderr)
        raise SystemExit(1)
